### ISSUE TITLE
[BUG] Error during launch of dask-cuda-worker

### ISSUE THREAD

**Issue by galipremsagar** [rapidsai/dask-cuda#100]
When I launch dask-cuda-worker from command line using following command I get error:

```bash
(rapids) root@dt07:/# dask-cuda-worker --scheduler-file=/home/nfs/pgali/del31 --no-bokeh --host=10.136.7.107
/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/nanny.py:138: UserWarning: The local_dir keyword has moved to local_directory
  warnings.warn("The local_dir keyword has moved to local_directory")
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/bin/dask-cuda-worker", line 11, in <module>
    load_entry_point('dask-cuda==0.9.0a0+20.g357ec2c.dirty', 'console_scripts', 'dask-cuda-worker')()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 323, in go
    main()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 314, in main
    loop.run_sync(run)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 307, in run
    yield [n._start(addr) for n in nannies]
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 307, in <listcomp>
    yield [n._start(addr) for n in nannies]
AttributeError: 'Nanny' object has no attribute '_start'
```

**Comment by mrocklin** [comment]
Yes, there have been some internal changes upstream that were just
released.  I'm working on this now.  Thanks for the clear issue.

**Comment by mrocklin** [comment]
See https://github.com/rapidsai/dask-cuda/pull/101

**Comment by pentschev** [comment]
This is in now. Thanks @galipremsagar for the report and @mrocklin for the fix. Closing.
