### ISSUE TITLE
Intentional type-errors on CuPY-backed dask arrays using interal CuPY methods? 

### ISSUE THREAD

**Issue by Joachimoe** [rapidsai/dask-cuda#1019]
When following the DaskCUDA tutorial, one way of casting an array to a CuPY array is doing the following:

```
rs = da.random.RandomState(RandomState=cp.random.RandomState)
rs = rs.randint(low = 0, high = 100_000, size = (1000, 1000, 1000), chunks = 'auto')
```
When type-checking this, it correctly creates an array of type ```dask.array``` with chunk-types of type ```cupy.ndarray```. 

The specific output is the following:
```
dask.array<randint, shape=(1000, 1000, 1000), dtype=int64, chunksize=(250, 250, 250), chunktype=cupy.ndarray>
``` 

If one calls ```cupyx.scipy.ndimage.rotate(rs, angle = 90)```one gets a type error:

```
Traceback (most recent call last):
  File "/home/joachim/Desktop/researchproject/src/pygpubatch/rotation.py", line 31, in <module>
    y = cupyx.scipy.ndimage.rotate(rs, angle = 90)
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupyx/scipy/ndimage/interpolation.py", line 562, in rotate
    return affine_transform(input, matrix, offset, output_shape, output, order,
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupyx/scipy/ndimage/interpolation.py", line 435, in affine_transform
    filtered, nprepad = _filter_input(input, prefilter, mode, cval, order)
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupyx/scipy/ndimage/interpolation.py", line 247, in _filter_input
    filtered = spline_filter(padded, order, output=float_dtype, mode=mode)
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupyx/scipy/ndimage/interpolation.py", line 178, in spline_filter
    temp, data_dtype, output_dtype = _get_spline_output(x, output)
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupyx/scipy/ndimage/interpolation.py", line 64, in _get_spline_output
    temp = cupy.ascontiguousarray(temp)
  File "/home/joachim/anaconda3/envs/rps/lib/python3.9/site-packages/cupy/_creation/from_data.py", line 107, in ascontiguousarray
    return _core.ascontiguousarray(a, dtype)
TypeError: Argument 'a' has incorrect type (expected cupy._core.core.ndarray, got Array)
``` 

Now, I get that the method is called on a dask.array type array. However, I have not seen how one can apply methods to the chunks specifically. As per my intuition, the type-check should happen to the chunk and not array, as the chunks are operated on. Maybe this intuition is wrong?

Here's a fully reproducible example:

```
import cupy as cp
import numpy as np
import dask.array as da
from dask_cuda import LocalCUDACluster
from dask.distributed import Client, wait
import rmm
import sys 
import cupyx.scipy.ndimage


if __name__ == '__main__':
    cluster = LocalCUDACluster('0', rmm_managed_memory=True)    ##This means that we use GPU device ID 0, and please give me the rapids memory manager 
    client = Client(cluster)                                    ##We create a local cluster here 
    client.run(cp.cuda.set_allocator, rmm.rmm_cupy_allocator)   ##We combine cupy and rmm to allocate memory on GPU 


    rmm.reinitialize(managed_memory=True)
    cp.cuda.set_allocator(rmm.rmm_cupy_allocator)


    #size = int(sys.argv[1])
    #wk   = int(sys.argv[2])

    rs = da.random.RandomState(RandomState=cp.random.RandomState)
    rs = rs.randint(low = 0, high = 100_000, size = (1000, 1000, 1000), chunks = 'auto')

    print(type(rs))
    y = cupyx.scipy.ndimage.rotate(rs, angle = 90).persist()
    wait(y)

```

System info:

```
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
arrow-cpp                 8.0.1           py39hd3ccb9b_2_cpu    conda-forge
aws-c-cal                 0.5.11               h95a6274_0    conda-forge
aws-c-common              0.6.2                h7f98852_0    conda-forge
aws-c-event-stream        0.2.7               h3541f99_13    conda-forge
aws-c-io                  0.10.5               hfb6a706_0    conda-forge
aws-checksums             0.1.11               ha31a3da_7    conda-forge
aws-sdk-cpp               1.8.186              hb4091e7_3    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.07.19           h06a4308_0  
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
carbontracker             1.1.6                    pypi_0    pypi
certifi                   2022.9.24        py39h06a4308_0  
cffi                      1.15.1           py39he91dace_0    conda-forge
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3            py39hf3d152e_0    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5                    pypi_0    pypi
cryptography              37.0.4           py39hd97740a_0    conda-forge
cuda-python               11.7.0           py39h3fd9d12_0    nvidia
cudatoolkit               11.5.1               hcf5317a_9    nvidia
cudf                      22.08.01        cuda_11_py39_g31337c9001_0    rapidsai
cuml                      22.08.00        cuda11_py39_g1e2f8a9aa_0    rapidsai
cupy                      10.6.0           py39hc3c280e_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.12.0           py39hb9d737c_0    conda-forge
dask                      2022.7.1           pyhd8ed1ab_0    conda-forge
dask-core                 2022.7.1           pyhd8ed1ab_0    conda-forge
dask-cuda                 22.08.00        py39_g9a61ce5_0    rapidsai
dask-cudf                 22.08.01        cuda_11_py39_g31337c9001_0    rapidsai
decorator                 5.1.1                    pypi_0    pypi
distributed               2022.7.1           pyhd8ed1ab_0    conda-forge
dlpack                    0.5                  h9c3ff4c_0    conda-forge
faiss-proc                1.0.0                      cuda    rapidsai
fastavro                  1.6.1            py39hb9d737c_0    conda-forge
fastrlock                 0.8              py39h5a03fae_2    conda-forge
fonttools                 4.37.4                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_0    conda-forge
fsspec                    2022.8.2           pyhd8ed1ab_0    conda-forge
future                    0.18.2                   pypi_0    pypi
geocoder                  1.38.1                   pypi_0    pypi
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.6.0                h6f12383_0    conda-forge
grpc-cpp                  1.47.1               hbad87ad_6    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h166bdaf_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20220623.0      cxx17_h48a1fff_4    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_7    conda-forge
libbrotlidec              1.0.9                h166bdaf_7    conda-forge
libbrotlienc              1.0.9                h166bdaf_7    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcudf                   22.08.01        cuda11_g31337c9001_0    rapidsai
libcuml                   22.08.00        cuda11_g1e2f8a9aa_0    rapidsai
libcumlprims              22.08.00        cuda11_g1770e60_0    nvidia
libcurl                   7.85.0               h7bff187_0    conda-forge
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libgoogle-cloud           2.1.0                h9ebe8e8_2    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libllvm11                 11.1.0               he0ac6c6_4    conda-forge
libnghttp2                1.47.0               hdcd2b5c_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.38               h753d276_0    conda-forge
libprotobuf               3.20.1               h6239696_4    conda-forge
libraft-distance          22.08.00        cuda11_g87a7d16c_0    rapidsai
libraft-headers           22.08.00        cuda11_g87a7d16c_0    rapidsai
libraft-nn                22.08.00        cuda11_g87a7d16c_0    rapidsai
librmm                    22.08.00        cuda11_gd212232c_0    rapidsai
libsqlite                 3.39.4               h753d276_0    conda-forge
libssh2                   1.10.0               haa6b8db_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libthrift                 0.16.0               h491838f_2    conda-forge
libtiff                   4.4.0                h55922b4_4    conda-forge
libutf8proc               2.7.0                h7f98852_0    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.12               h166bdaf_4    conda-forge
llvmlite                  0.39.1           py39h7d9a04d_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lz4                       4.0.0            py39h029007f_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.1.1            py39hb9d737c_1    conda-forge
matplotlib                3.6.0                    pypi_0    pypi
msgpack-python            1.0.4            py39hf939315_0    conda-forge
nccl                      2.14.3.1             h0800d71_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
numba                     0.56.2           py39h61ddf18_1    conda-forge
numpy                     1.22.4           py39hc58783e_0    conda-forge
nvtx                      0.2.3            py39h3811e60_1    conda-forge
openjpeg                  2.5.0                h7d73246_1    conda-forge
openssl                   1.1.1q               h7f8727e_0  
orc                       1.7.6                h6c59b99_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.4            py39h1832856_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pillow                    9.2.0            py39hd5dbb17_2    conda-forge
pip                       22.2.2           py39h06a4308_0  
protobuf                  3.20.1           py39h5a03fae_0    conda-forge
psutil                    5.9.2            py39hb9d737c_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptxcompiler               0.2.0            py39h107f55c_0    rapidsai
pyarrow                   8.0.1           py39hc0775d8_2_cpu    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pynvml                    11.4.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyraft                    22.08.00        cuda11_py39_g87a7d16c_0    rapidsai
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.13          h9a8a25e_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.4             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
ratelim                   0.1.6                    pypi_0    pypi
re2                       2022.06.01           h27087fc_0    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
rmm                       22.08.00        cuda11_py39_gd212232c_0    rapidsai
s2n                       1.0.10               h9b69904_0    conda-forge
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.1            py39h8ba3f38_0    conda-forge
seaborn                   0.12.0                   pypi_0    pypi
setuptools                65.4.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sklearn                   0.0                      pypi_0    pypi
snappy                    1.1.9                hbd366e4_1    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
spdlog                    1.8.5                h4bd325d_1    conda-forge
sqlite                    3.39.4               h4ff8645_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39hb9d737c_3    conda-forge
treelite                  2.4.0            py39h6b629c6_1    conda-forge
treelite-runtime          2.4.0                    pypi_0    pypi
typing_extensions         4.3.0              pyha770c72_0    conda-forge
tzdata                    2022d                h191b570_0    conda-forge
ucx                       1.13.1               h538f049_0    conda-forge
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.27.00         py39_g9abe3c1_0    rapidsai
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.12               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by pentschev** [comment]
You can't call a CuPy function directly on a Dask array, CuPy only operate on CuPy arrays. For what you want to do, you need to implement that in Dask, and what you're looking for is probably [`map_blocks`](https://docs.dask.org/en/latest/generated/dask.array.map_blocks.html) or [`map_overlap`](https://docs.dask.org/en/latest/generated/dask.array.map_overlap.html).

I'm not familiar with everything that's supported but you may want to give a look at https://github.com/dask/dask-image, it has some CuPy support out-of-the-box, including for affine transformations, in particular https://github.com/dask/dask-image/blob/b8ff7d9d370750a0074cd7d973329f79669fbc05/tests/test_dask_image/test_ndinterp/test_affine_transformation.py#L66-L68 may give you a hint on what you're trying to do, but maybe you'll be able to just use dask-image instead of doing that work by hand.

**Comment by Joachimoe** [comment]
Thank you for your reply. 

Looks like I'll have to do it myself, as the rotation is not implemented in dask_image. However, it is implemented in:

When looking at: https://docs.dask.org/en/stable/generated/dask.array.rot90.html

It is implemented as: 

```@derived_from(np)
def rot90(m, k=1, axes=(0, 1)):
    axes = tuple(axes)
    if len(axes) != 2:
        raise ValueError("len(axes) must be 2.")

    m = asanyarray(m)

    if axes[0] == axes[1] or np.absolute(axes[0] - axes[1]) == m.ndim:
        raise ValueError("Axes must be different.")

    if axes[0] >= m.ndim or axes[0] < -m.ndim or axes[1] >= m.ndim or axes[1] < -m.ndim:
        raise ValueError(f"Axes={axes} out of range for array of ndim={m.ndim}.")

    k %= 4

    if k == 0:
        return m[:]
    if k == 2:
        return flip(flip(m, axes[0]), axes[1])

    axes_list = list(range(0, m.ndim))
    (axes_list[axes[0]], axes_list[axes[1]]) = (axes_list[axes[1]], axes_list[axes[0]])

    if k == 1:
        return transpose(flip(m, axes[1]), axes_list)
    else:
        # k == 3
        return flip(transpose(m, axes_list), axes[1])
```
The documentation states that this method  "returns a rotated view of m", and not the rotated array. 


The numpy version returns a rotated view, because ```np.flip``` returns "A view of m with the entries of axis reversed. Since a view is returned, this operation is done in constant time", source: https://numpy.org/doc/stable/reference/generated/numpy.flip.html 

The dask documentation states that it "returns the flipped array", source: https://docs.dask.org/en/latest/generated/dask.array.flip.html

Now the return type of dask.array.rot90 depends on $k$, where ```transpose``` is called on the flipped array. This returns "a with its axes permuted. A view is returned whenever possible."

So what does dask.rot90 return? A view, or the rotated matrix? I am confused because the dask documentation says that flip returns an actually flipped array, why rot90 can, if k == 3, return the actually flipped array and not a view?
