### ISSUE TITLE
LocalCUDACluster throws an Exception on only one Node

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/dask-cuda#1022]
Repro:
```
In [1]: from dask_cuda import LocalCUDACluster
In [2]: c = LocalCUDACluster()

2022-10-19 16:16:12,153 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 16:16:12,153 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-19 16:16:12,161 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 16:16:12,162 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-19 16:16:12,167 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 16:16:12,168 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.12/lib/python3.9/site-packages/dask_cuda/initialize.py", line 31, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.12/lib/python3.9/site-packages/distributed/comm/ucx.py", line 92, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.12/lib/python3.9/site-packages/distributed/comm/ucx.py", line 602, in _scrub_ucx_config
    valid_ucx_vars = list(get_config().keys())
  File "/conda/envs/rapids-22.12/lib/python3.9/site-packages/ucp/core.py", line 986, in get_config
    return ucx_api.get_current_options()
  File "ucp/_libs/utils.pyx", line 174, in ucp._libs.ucx_api.get_current_options
  File "ucp/_libs/utils.pyx", line 155, in ucp._libs.ucx_api.ucx_config_to_dict
  File "ucp/_libs/utils.pyx", line 34, in ucp._libs.ucx_api.create_text_fd
OSError: tmpfile() failed


In [3]: c
Out[3]: LocalCUDACluster(8c6f46c9, 'tcp://127.0.0.1:35409', workers=4, threads=4, memory=754.40 GiB)
```

**Comment by mlahir1** [comment]
pre context:

LocalCUDACluster was causing a crash, when we debug, looked like one of the GPU had a double bit error
```
    Retired Pages
        Single Bit ECC                    : 0
        Double Bit ECC                    : 6
        Pending Page Blacklist            : Yes
      
```
I re-started the machine upon suggestion from NVIDIA team and Pending Page Blacklist is set back to No,
```
GPU 00000000:B3:00.0
    Retired Pages
        Single Bit ECC                    : 0
        Double Bit ECC                    : 6
        Pending Page Blacklist            : No
```

i was advised that seg fault could be fixed by this: https://github.com/rapidsai/ucx-py/pull/889

how ever seg fault is fixed, i am still running into following exception.

**Comment by jakirkham** [comment]
Could you please try with [the latest `ucx-py` nightly from the `rapidsai-nightly` channel]( https://anaconda.org/rapidsai-nightly/ucx-py ) and share the results?

**Comment by pentschev** [comment]
The problem here is the source of the exception, which is https://github.com/rapidsai/ucx-py/blob/9f5ff1f504b54e1d1bdd966bb0857131398c808d/ucp/_libs/utils.pyx#L32 , this is a very simple C call to [tmpfile](https://en.cppreference.com/w/c/io/tmpfile).

The title suggests this only happens on one node, but not in all others, whatever number of nodes you have (assuming > 1). In that case, it seems like the system is having some trouble in creating a temporary file, which is _very_ unusual and I can't even seem to find any cases for that on Linux. Just to be sure, this is running on Linux, not WSL2, right?

On Linux what I can think of doing next is [increasing the maximum number of file descriptors](https://ucx-py.readthedocs.io/en/latest/os-limits.html#file-descriptors), but I'm not sure if that is the reason and whether it will solve that.

**Comment by mlahir1** [comment]
As a part of the GPU Lab we have 12 Nodes with 8 V100 each. this exception is only happening on one of those which is very weird. All of them run the same OS and cuda Driver versions too.


yes, its running on Linux,

```
root@3e2964741c3a:~# cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by jakirkham** [comment]
What happens if `mktemp` is run?

**Comment by mlahir1** [comment]
yes, that fixes it. looks like /tmp file is not present.
interesting how that got deleted.
```
root@3e2964741c3a:~# mktemp /tmp/example.XXXXXXXXXX
mktemp: failed to create file via template '/tmp/example.XXXXXXXXXX': No such file or directory
root@3e2964741c3a:~# ls /tmp
ls: cannot access '/tmp': No such file or directory
root@3e2964741c3a:~# mkdir /tmp
root@3e2964741c3a:~# mktemp /tmp/example.XXXXXXXXXX
/tmp/example.SUH33oYz7C
```

able to run fine now.
```
In [1]: from dask_cuda import LocalCUDACluster

In [2]: c= LocalCUDACluster()
2022-10-19 18:34:04,067 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 18:34:04,068 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-19 18:34:04,075 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 18:34:04,075 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-19 18:34:04,091 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 18:34:04,091 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
2022-10-19 18:34:04,098 - distributed.preloading - INFO - Creating preload: dask_cuda.initialize
2022-10-19 18:34:04,098 - distributed.preloading - INFO - Import preload module: dask_cuda.initialize
```

**Comment by pentschev** [comment]
Great, glad it was something simple, and it's really unfortunate we can't have a more comprehensive message from the OS.

**Comment by jakirkham** [comment]
Great! Thanks for the update. Glad things are working now 😄
