### ISSUE TITLE
Explicit comms tests are flaky

### ISSUE THREAD

**Issue by pentschev** [rapidsai/dask-cuda#1134]
Some of the tests have been flaky recently, below is the error I've been seeing intermittently and CI is reporting too:

<details>

```python
dask_cuda/tests/test_explicit_comms.py::test_dataframe_merge_empty_partitions 2023-02-28 00:37:48,547 - distributed.worker - WARNING - Compute Failed
Key:       ('hash-join-7dae9d6b2e7c044e324b6d2a6e08d260', 0)
Function:  merge_unpack
args:      ('d09b2cef837027208a4f75148f99850f', '75a427a6d81e8655bbcd7c2fefbe8007', 0, 3, 1, 'inner', ['key'], ['key'],    key  payload1  payload2
0    1         1         1
1    1         1         1
2    1         1         1
3    1         1         1, ('_x', '_y'))
kwargs:    {}
Exception: 'AttributeError("\'DataFrame\' object has no attribute \'header\'")'

2023-02-28 00:37:48,547 - distributed.worker - WARNING - Compute Failed
Key:       ('hash-join-7dae9d6b2e7c044e324b6d2a6e08d260', 1)
Function:  merge_unpack
args:      ('d09b2cef837027208a4f75148f99850f', '75a427a6d81e8655bbcd7c2fefbe8007', 1, 3, 1, 'inner', ['key'], ['key'],    key  payload1  payload2
0    1         1         1
1    1         1         1
2    1         1         1
3    1         1         1, ('_x', '_y'))
kwargs:    {}
Exception: 'AttributeError("\'DataFrame\' object has no attribute \'header\'")'

2023-02-28 00:37:48,684 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:41884 remote=tcp://127.0.0.1:33281>: Stream is closed
2023-02-28 00:37:48,685 - distributed.worker - ERROR - Failed to communicate with scheduler during heartbeat.
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 225, in read
    frames_nbytes = await stream.read_bytes(fmt_size)
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/worker.py", line 1237, in heartbeat
    response = await retry_operation(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils_comm.py", line 434, in retry_operation
    return await retry(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils_comm.py", line 413, in retry
    return await coro()
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/core.py", line 1227, in send_recv_from_rpc
    return await send_recv(comm=comm, op=key, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/core.py", line 986, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 241, in read
    convert_stream_closed_error(self, e)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/comm/tcp.py", line 144, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) ConnectionPool.heartbeat_worker local=tcp://127.0.0.1:41880 remote=tcp://127.0.0.1:33281>: Stream is closed
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/datasets/pentschev/src/dask-cuda/dask_cuda/tests/test_explicit_comms.py", line 84, in _test_dataframe_merge_empty_partitions
    ddf3 = ddf1.merge(ddf2, on=["key"]).set_index("key")
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/dask/dataframe/core.py", line 5188, in set_index
    return set_index(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/dask/dataframe/shuffle.py", line 227, in set_index
    divisions, mins, maxes = _calculate_divisions(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/dask/dataframe/shuffle.py", line 47, in _calculate_divisions
    divisions, sizes, mins, maxes = compute(divisions, sizes, mins, maxes)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/dask/base.py", line 599, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/client.py", line 3136, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/client.py", line 2305, in gather
    return self.sync(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils.py", line 338, in sync
    return sync(
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils.py", line 405, in sync
    raise exc.with_traceback(tb)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/utils.py", line 378, in f
    result = yield future
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/tornado/gen.py", line 769, in run
    value = future.result()
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/client.py", line 2168, in _gather
    raise exception.with_traceback(traceback)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/distributed/shuffle/_merge.py", line 171, in merge_unpack
    result_meta = deserialize(result_meta.header, result_meta.frames)
  File "/datasets/pentschev/miniconda3/envs/rn-230228/lib/python3.10/site-packages/pandas/core/generic.py", line 5902, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'header'
FAILED
```

</details>

Besides `test_dataframe_merge_empty_partitions`, I've seen the same error in at least `test_dataframe_shuffle_merge[tcp-pandas-4]` and `test_dataframe_shuffle_merge[ucx-pandas-4]`. @madsbk do you know if anything has recently changed that could have caused this?

**Comment by madsbk** [comment]
Should be fixed in https://github.com/rapidsai/dask-cuda/pull/1135
