### ISSUE TITLE
Pynvml issues when running LocalCudaCluster

### ISSUE THREAD

**Issue by jacobtomlinson** [rapidsai/dask-cuda#122]
```console
$ conda create -n testenv -c rapidsai -c conda-forge python=3.7 ipython distributed==2.3.0 dask-cuda==0.9.0 pynvml
```

```python
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
```

```python-traceback
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/nanny.py", line 674, in run
    await worker
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/worker.py", line 1016, in start
    await self._register_with_scheduler()
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/worker.py", line 811, in _register_with_scheduler
    metrics=await self.get_metrics(),
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/worker.py", line 740, in get_metrics
    result = await result
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/worker.py", line 3406, in gpu_metric
    result = yield offload(nvml.real_time)
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/utils.py", line 1489, in offload
    return (yield _offload_executor.submit(fn, *args, **kwargs))
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/nfs/bzaitlen/miniconda3/envs/cudf-dev/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/diagnostics/nvml.py", line 11, in real_time
    "utilization": [pynvml.nvmlDeviceGetUtilizationRates(h).gpu for h in handles],
  File "/home/nfs/bzaitlen/GitRepos/distributed/distributed/diagnostics/nvml.py", line 11, in <listcomp>
    "utilization": [pynvml.nvmlDeviceGetUtilizationRates(h).gpu for h in handles],
  File "/home/nfs/bzaitlen/GitRepos/pynvml/pynvml/nvml.py", line 1347, in nvmlDeviceGetUtilizationRates
    check_return(ret)
  File "/home/nfs/bzaitlen/GitRepos/pynvml/pynvml/nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized


pynvml.nvml.NVMLError_Uninitialized: Uninitialized
```

This is giving the same error that was raised in gpuopenanalytics/pynvml#16.

Note that if you do not install `pynvml` into the environment this doesn't happen.

**Comment by mrocklin** [comment]
So, we do seem to initialize pynvml here:

https://github.com/dask/distributed/blob/58b3abe6d2e5b9898344ba87f93c20648247507e/distributed/diagnostics/nvml.py#L1-L4

I don't have a strong understanding of why this might fail.  cc'ing @rjzamora in case he has thoughts.

Regardless, we should probably make sure that things don't fail, if this fails, and that we instead gracefully avoid this functionality.

**Comment by mrocklin** [comment]
Dask is made robust here https://github.com/dask/distributed/pull/2984


We should probably figure out why nvml wasn't initialized though.

**Comment by rjzamora** [comment]
> I don't have a strong understanding of why this might fail. cc'ing @rjzamora in case he has thoughts.

I'm trying to reproduce this to see what the problem is.  However, I am having trouble reproducing (using the same conda environment defined above).

**Comment by jacobtomlinson** [comment]
dask/distributed#2984 has resolved the symptoms of this in that the exception is passed over. However it doesn't actually solve the problem of `pynvml` not loading correctly.

I'm going to reopen this to track solving this problem in the long term.

**Comment by jacobtomlinson** [comment]
I can continue to reproduce this issue with the conda environment above and distributed master by running:

```python
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
assert 'nvml' in cluster.scheduler.workers[cluster.scheduler.workers.keys()[0]].metrics
```

```python-traceback
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-11-2b9d4ef220e7> in <module>
----> 1 assert 'nvml' in cluster.scheduler.workers[cluster.scheduler.workers.keys()[0]].metrics

AssertionError: 
```

**Comment by rjzamora** [comment]
Hmm. For me, `cluster.scheduler.workers[cluster.scheduler.workers.keys()[0]].metrics` returns:

```
{'gpu': {'utilization': (0, 0, 0, 0, 0, 0, 0, 0),
  'memory-used': (867762176,
   439943168,
   439943168,
   439943168,
   439943168,
   439943168,
   439943168,
   439943168)},
 'cpu': 4.0,
 'memory': 300892160,
 'time': 1566492751.497705,
 'read_bytes': 83720.24666674293,
 'write_bytes': 9994.77659456842,
 'num_fds': 91,
 'executing': 0,
 'in_memory': 0,
 'ready': 0,
 'in_flight': 0,
 'bandwidth': 100000000}
```

This does not include `'nvml'`, so that assertion fails, but the output makes sense to me?

**Comment by jacobtomlinson** [comment]
Sorry should be `gpu`. Updated above.

**Comment by pentschev** [comment]
It seems this is fixed, can you confirm that @jacobtomlinson ? Note that dask-cuda now depends on pynvml since #138 has been merged.

**Comment by jacobtomlinson** [comment]
Just tested again now with distributed `2.4.0` and dask-cuda `0.9.1`.

```console
$ conda create -n testenv -c rapidsai -c conda-forge python=3.7 ipython distributed==2.4.0 dask-cuda==0.9.1 pynvml
```

```python
from dask_cuda import LocalCUDACluster
cluster = LocalCUDACluster()
```

When running this I am hitting into #132. However, if I then go on to run `pip install git+https://github.com/rapidsai/dask-cuda.git` everything works as expected.

**Comment by mrocklin** [comment]
So maybe everything will be ok as of the next release?

**Comment by pentschev** [comment]
Yes, I recommend using `dask-cuda=0.10` (from `rapidsai-nightly`). Alternatively, it should work with `distributed==2.3.2`.

**Comment by jacobtomlinson** [comment]
Fair enough. I'm confident that this specific issue is closed.

**Comment by CallShaul** [comment]
Having issue running: "cluster = dask_cuda.LocalCUDACluster()" Using Python 3.8.5 on Windows 10, with CUDA 11.2 and latest drives, (2xRTX 3090)

Tried copying missing file as mentioned in the Nvidia forum:
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/295198/nvmldll-and-nvsmi-folder-missing/

Now getting this error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 150, in get_n_gpus
    return len(os.environ["CUDA_VISIBLE_DEVICES"].split(","))
  File "C:\ProgramData\Anaconda3\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\toolz\functoolz.py", line 456, in memof
    return cache[k]
KeyError: ()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0e41b44ee01c>", line 1, in <module>
    cluster = dask_cuda.LocalCUDACluster()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\local_cuda_cluster.py", line 151, in __init__
    CUDA_VISIBLE_DEVICES = cuda_visible_devices(0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 442, in cuda_visible_devices
    visible = range(get_n_gpus())
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 152, in get_n_gpus
    return get_gpu_count()
  File "C:\ProgramData\Anaconda3\lib\site-packages\toolz\functoolz.py", line 460, in memof
    cache[k] = result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 102, in get_gpu_count
    pynvml.nvmlInit()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 749, in nvmlInit
    check_return(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized

running nvidia-smi yields:

![image](https://user-images.githubusercontent.com/52006780/102014643-ad15b300-3d5f-11eb-8394-9c12fd3cb2e6.png)

**Comment by jacobtomlinson** [comment]
@CallShaul I'm afraid RAPIDS does not support Windows.
