### ISSUE TITLE
RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.

### ISSUE THREAD

**Issue by loretoparisi** [rapidsai/dask-cuda#1415]
# Error
```
Traceback (most recent call last):
  File "/home/coder/.local/lib/python3.10/site-packages/distributed/nanny.py", line 452, in instantiate
    result = await self.process.start()
  File "/home/coder/.local/lib/python3.10/site-packages/distributed/nanny.py", line 749, in start
    await self.process.start()
  File "/home/coder/.local/lib/python3.10/site-packages/distributed/process.py", line 55, in _call_and_set_future
    res = func(*args, **kwargs)
  File "/home/coder/.local/lib/python3.10/site-packages/distributed/process.py", line 215, in _start
    process.start()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```
# Version

```
pip install dask-cudf-cu12
pip install rmm-cu12
```

# Code

```python
import cudf 
from dask.distributed import Client, wait, get_worker, get_client 
from dask_cuda import LocalCUDACluster 
import dask.dataframe as dd 
import pandas as pd 
import random 

cluster = LocalCUDACluster(CUDA_VISIBLE_DEVICES="0,1,2,3", n_workers=4, threads_per_worker=4, memory_limit="12GB",  device_memory_limit="20GB", rmm_pool_size="2GB", rmm_maximum_pool_size="10GB") 

client = Client(cluster) 

client.run(cudf.set_allocator, "managed") 

worker_info = client.scheduler_info()["workers"] 

for worker, info in worker_info.items(): 
    print(worker) 

# tcp://127.x.x.x:xxxxxx 
# tcp://127.x.x.x:xxxxxx 

df = pd.DataFrame({'col_1':random.sample(range(10**3), 10**3), 'col_2': random.sample(range(10**3), 10**3) }) 

ddf = dd.from_pandas(df, npartitions=8) 

def test_f(df, col_1, col_2):
     return df.assign(result=df[col_1]*df[col_2])

ddf_out = ddf.map_partitions(test_f, 'col_1', 'col_2',  meta={'col_1':'int64', 'col_2':'int64', 'result':'int64'}) 
```

**Comment by pentschev** [comment]
Please refer to the [Dask-CUDA quickstart guide](https://docs.rapids.ai/api/dask-cuda/stable/quickstart/#localcudacluster) and [Distributed docs on Python standalone scripts](https://docs.dask.org/en/stable/scheduling.html#standalone-python-scripts) that document this case and how to resolve it.
