### ISSUE TITLE
[BUG]  Setting memory limit to zero causes `pickling` errors with `dlmc/xgboost`

### ISSUE THREAD

**Issue by VibhuJawa** [rapidsai/dask-cuda#150]
### [BUG]  Setting memory limit to zero causes `pickling` errors with `xgboost`. 

When i try creating `dmatrices` with `delayed-cudf`  objects and the memory limit is `0` . It does not happen when `memory limit ` is a big number. 

### Note : 

To install `xgboost` you may need to do a `pip` install for the `dlmc/xgboost` (depending on the nightly you have). 

```
pip install https://xgboost-ci.net/job/xgboost/job/master/lastSuccessfulBuild/artifact/python-package/dist/xgboost-1.0.0_SNAPSHOT-py2.py3-none-any.whl
```

### Notebook:
https://nbviewer.jupyter.org/gist/VibhuJawa/d5aa8a21d6e771f606267ff01e14b5f3

###  Minimal Example: 

```python
#### import libraries
import xgboost 
import dask_cudf
import numpy as np
from dask.distributed import Client, wait
from dask.dataframe import from_delayed
import cudf
import dask
from dask_cuda import LocalCUDACluster


#### start client
### does not occur if i set memory limit to a bug  number
# cluster = LocalCUDACluster(memory_limit = '100 GB')

### memory limit = 0
## below causes pickling errors 
cluster = LocalCUDACluster(memory_limit = 0)

client = Client(cluster)
client


### create dataframe
df = dask_cudf.from_cudf(cudf.DataFrame({'x':np.ones(shape = 1_000_000),'y':np.ones(shape = 1_000_000)}), npartitions=8)
df = df.persist()
done = wait(df)


def get_dmatrix_from_persisted_df(df,label_col = 'y',non_label_columns=['x']):
    gpu_dfs = [(gpu_df[[label_col]], gpu_df[non_label_columns]) for gpu_df in df.to_delayed()]
    gpu_dfs = [(gpu_df[0].persist(), gpu_df[1].persist()) for gpu_df in gpu_dfs]

    dmat_ls = [dask.delayed(xgboost.DMatrix)(gpu_df[1], gpu_df[0]) for gpu_df in gpu_dfs]
    dmat_ls = [dmat.persist() for dmat in dmat_ls]
    wait(dmat_ls)
    
    return dmat_ls

### Hangs here if i use * memory limit = 0 , does not hang if memory_limit is a big number * 

dmat = get_dmatrix_from_persisted_df(df)

````

Stack Trace:
```python
distributed.worker - ERROR - Could not serialize object of type DMatrix.
````

Full Stack Trace:

```python
distributed.worker - ERROR - Could not serialize object of type DMatrix. Traceback (most recent call last): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) ValueError: ctypes objects containing pointers cannot be pickled During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize header, frames = dumps(x, context=context) if wants_context else dumps(x) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 58, in pickle_dumps return {"serializer": "pickle"}, [pickle.dumps(x)] File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps cp.dump(obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump return Pickler.dump(self, obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 437, in dump self.save(obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 549, in save self.save_reduce(obj=obj, *rv) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 662, in save_reduce save(state) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 856, in save_dict self._batch_setitems(obj.items()) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 882, in _batch_setitems save(v) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 524, in save rv = reduce(self.proto) ValueError: ctypes objects containing pointers cannot be pickled Traceback (most recent call last): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/worker.py", line 1632, in transition_executing_done self.send_task_state_to_scheduler(key) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/worker.py", line 1788, in send_task_state_to_scheduler if key in self.data or self.actors.get(key): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/_collections_abc.py", line 666, in __contains__ self[key] File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/dask_cuda/device_host_file.py", line 154, in __getitem__ return self.host_buffer[key] File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/zict/buffer.py", line 70, in __getitem__ return self.slow_to_fast(key) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/zict/buffer.py", line 57, in slow_to_fast value = self.slow[key] File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/zict/func.py", line 39, in __getitem__ return self.load(self.d[key]) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 468, in deserialize_bytes return deserialize(header, frames) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 268, in deserialize return loads(header, frames) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 80, in serialization_error_loads raise TypeError(msg) TypeError: Could not serialize object of type DMatrix. Traceback (most recent call last): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 38, in dumps result = pickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) ValueError: ctypes objects containing pointers cannot be pickled During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 191, in serialize header, frames = dumps(x, context=context) if wants_context else dumps(x) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 58, in pickle_dumps return {"serializer": "pickle"}, [pickle.dumps(x)] File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 51, in dumps return cloudpickle.dumps(x, protocol=pickle.HIGHEST_PROTOCOL) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 1125, in dumps cp.dump(obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 482, in dump return Pickler.dump(self, obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 437, in dump self.save(obj) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 549, in save self.save_reduce(obj=obj, *rv) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 662, in save_reduce save(state) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 504, in save f(self, obj) # Call unbound method with explicit self File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 856, in save_dict self._batch_setitems(obj.items()) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 882, in _batch_setitems save(v) File "/home/nfs/vjawa/anaconda3/envs/RAPIDS/lib/python3.7/pickle.py", line 524, in save rv = reduce(self.proto) ValueError: ctypes objects containing pointers cannot be pickled
```

**Comment by pentschev** [comment]
Sorry, I missed this. By the looks of it, I believe https://github.com/rapidsai/dask-cuda/pull/269 should have solved this problem. I'm tentatively closing this, please reopen if I'm mistaken @VibhuJawa .

**Comment by jakirkham** [comment]
Agree it sounds like this was fixed.

It's worth noting independently that Dask doesn't know how to serialize a `DMatrix` object. This can be fixed by implementing pickling for `DMatrix` as a first step. Though better still will be to implement Dask's custom serialization for `DMatrix`.

cc @hcho3 (in case this serialization problem is also of interest 😉)
