### ISSUE TITLE
dask-cuda worker failure in multinode environemnt

### ISSUE THREAD

**Issue by pradghos** [rapidsai/dask-cuda#165]
Test Scenario : 

1. Started `dask-cuda-cluster` with two multinode -  

2. Cluster information - 
```
Client

    Scheduler: tcp://<scheduler ip information>
    Dashboard: http://<scheduler ip information>/status 
Cluster

    Workers: 8
    Cores: 8
    Memory: 55.44 GB
```

3.  then using `dask-xgboost` to train the model -    
    dxgb.train(client, params, data_train, labels_train)
    dataset size before the test and train split: 544M , data_train.compute().shape - `5115379, 428`.

Log : Dask-cuda-worker log :- 

```
distributed.worker - DEBUG - Calling gc.collect(). 6.305s elapsed since previous call.
distributed.worker - DEBUG - gc.collect() took 0.039s
distributed.worker - WARNING - Worker is at 84% memory usage. Pausing worker.  Process memory: 6.39 GB -- Worker memory limit: 7.26 GB
distributed.nanny - WARNING - Worker exceeded 95% memory budget. Restarting
distributed.nanny - INFO - Worker process 79862 was killed by signal 15
distributed.nanny - WARNING - Restarting worker
distributed.worker - DEBUG - future state: train_part-2166870f97e063bb06fb6d64d0ff334c - RUNNING
distributed.worker - DEBUG - future state: train_part-19d6c31a81b514786bb5597eab5fbe3b - RUNNING
distributed.worker - DEBUG - future state: train_part-f34f400d4607914244d362934c2b1b79 - RUNNING
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:37263
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42609
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39685
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:37263
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42609
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39685
distributed.worker - DEBUG - Moved 1 pieces of data data and 266.65 MB to disk
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 6.13 GB -- Worker memory limit: 7.26 GB
distributed.worker - DEBUG - Moved 3 pieces of data data and 572.41 MB to disk
distributed.worker - DEBUG - future state: train_part-f34f400d4607914244d362934c2b1b79 - RUNNING
distributed.worker - DEBUG - future state: train_part-2166870f97e063bb06fb6d64d0ff334c - RUNNING
distributed.worker - DEBUG - future state: train_part-19d6c31a81b514786bb5597eab5fbe3b - RUNNING
distributed.worker - WARNING - Memory use is high but worker has no data to store to disk.  Perhaps some other process is leaking memory?  Process memory: 6.08 GB -- Worker memory limit: 7.26 GB

```

Followed by the below log - 

```

distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - WARNING - Worker is at 55% memory usage. Resuming worker. Process memory: 4.05 GB -- Worker memory limit: 7.26 GB
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 674, in run
    await worker
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 1023, in start
    await self._register_with_scheduler()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 795, in _register_with_scheduler
    types = {k: typename(v) for k, v in self.data.items()}
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 795, in <dictcomp>
    types = {k: typename(v) for k, v in self.data.items()}
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 382, in _on_exit
    await self.instantiate()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 321, in instantiate
    result = await self.process.start()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 492, in start
    msg = await self._wait_until_connected(uid)
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 606, in _wait_until_connected
    raise msg
TypeError: exceptions must derive from BaseException
distributed.nanny - WARNING - Restarting worker
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.worker - DEBUG - future state: train_part-896f51f320f44f2854459157657285ff - RUNNING
distributed.worker - DEBUG - future state: train_part-cd53396ddfa0f34adb9b75dc5e91340e - RUNNING
distributed.worker - DEBUG - future state: train_part-df9cae317144e8740c66cf8b35853472 - RUNNING
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.diskutils - INFO - Found stale lock file and directory '/tmp/machine1_dask/dask-worker-space/worker-hc7riuc1', purging
distributed.preloading - INFO - Import preload module: dask_cuda.initialize_context
distributed.worker - INFO -       Start worker at:     tcp://9.3.89.155:40653
distributed.worker - INFO -          Listening to:     tcp://9.3.89.155:40653
distributed.worker - INFO -          dashboard at:           9.3.89.155:41885
distributed.worker - INFO - Waiting to connect to:       tcp://9.3.89.41:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    7.26 GB
distributed.worker - INFO -       Local Directory: /tmp/machine1_dask/dask-worker-space/worker-wjxfgr3f
distributed.worker - INFO - -------------------------------------------------
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.worker - DEBUG - future state: train_part-896f51f320f44f2854459157657285ff - RUNNING
distributed.worker - DEBUG - future state: train_part-df9cae317144e8740c66cf8b35853472 - RUNNING
distributed.worker - DEBUG - future state: train_part-cd53396ddfa0f34adb9b75dc5e91340e - RUNNING
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 674, in run
    await worker
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 1023, in start
    await self._register_with_scheduler()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 795, in _register_with_scheduler
    types = {k: typename(v) for k, v in self.data.items()}
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/worker.py", line 795, in <dictcomp>
    types = {k: typename(v) for k, v in self.data.items()}
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to restart worker after its process exited
Traceback (most recent call last):
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 382, in _on_exit
    await self.instantiate()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 321, in instantiate
    result = await self.process.start()
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 492, in start
    msg = await self._wait_until_connected(uid)
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/nanny.py", line 606, in _wait_until_connected
    raise msg
TypeError: exceptions must derive from BaseException
distributed.nanny - WARNING - Restarting worker
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:39691
distributed.diskutils - INFO - Found stale lock file and directory '/tmp/machine1_dask/dask-worker-space/worker-wjxfgr3f', purging
distributed.worker - DEBUG - future state: train_part-896f51f320f44f2854459157657285ff - RUNNING
distributed.worker - DEBUG - future state: train_part-df9cae317144e8740c66cf8b35853472 - RUNNING
distributed.worker - DEBUG - future state: train_part-cd53396ddfa0f34adb9b75dc5e91340e - RUNNING
distributed.preloading - INFO - Import preload module: dask_cuda.initialize_context
distributed.worker - INFO -       Start worker at:     tcp://9.3.89.155:37259
distributed.worker - INFO -          Listening to:     tcp://9.3.89.155:37259
distributed.worker - INFO -          dashboard at:           9.3.89.155:45109
distributed.worker - INFO - Waiting to connect to:       tcp://9.3.89.41:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                    7.26 GB
distributed.worker - INFO -       Local Directory: /tmp/machine1_dask/dask-worker-space/worker-udxwnwsf
distributed.worker - INFO - -------------------------------------------------
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:42751
distributed.worker - DEBUG - Heartbeat: tcp://9.3.89.155:32991
distributed.protocol.pickle - INFO - Failed to deserialize b'\x80\x04\x95\n\x16\x00\x00\x00\x00\x00\x00\x8c\x11pandas.core.frame\x94\x8c\tDataFrame\x94\x93\x94)\x81\x94}\x94(\x8c\x05_data\x94\x8c\x1epandas.core.internals.managers\x94\x8c\x0cBlockManager\x94\x93\x94)\x81\x94(]\x94(\x8c\x18pandas.core.indexes.base\x94\x8c\n_new_Index\x94\x93\x94h\x0b\x8c\x05Index\x94\x93\x94}\x94(\x8c\x04data\x94\x8c\x15numpy.core.multiarray\x94\x8c\x0c_reconstruct\x94\x93\x94\x8c\x05numpy\x94\x8c\x07ndarray\x94\x93\x94K\x00\x85\x94C\x01b\x94\x87\x94R\x94(K\x01M\

x02\x00\x00\x00\x00\x00\x00S\x02\x00\x00\x00\x00\x00\x00T\x02\x00\x00\x00\x00\x00\x00U\x02\x00\x00\x00\x00\x00\x00V\x02\x00\x00\x00\x00\x00\x00W\x02\x00\x00\x00\x00\x00\x00X\x02\x00\x00\x00\x00\x00\x00Y\x02\x00\x00\x00\x00\x00\x00Z\x02\x00\x00\x00\x00\x00\x00[\x02\x00\x00\x00\x00\x00\x00\\\x02\x00\x00\x00\x00'
Traceback (most recent call last):
  File "/mnt/test1/home/user1/anaconda3/envs/xgb-test/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 59, in loads
    return pickle.loads(x)
_pickle.UnpicklingError: pickle data was truncated
distributed.nanny - ERROR - Failed to start worker

```

Version : 
```
(xgb-test) [user1@machine1 machine1_dask]$ conda list | grep python
ipython                   7.8.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
msgpack-python            0.6.1            py37hfd86e86_1
python                    3.7.4                h2bede3c_1
python-dateutil           2.8.0                    py37_0
(xgb-test) [user1@machine1 machine1_dask]$ conda list | grep dask-cuda
dask-cuda                 0.9.1           py37_572.g9af8baa    
(xgb-test) [user1@machine1 machine1_dask]$ conda list | grep dask
dask                      2.3.0                      py_0
dask-core                 2.3.0                      py_0
dask-cuda                 0.9.1           py37_572.g9af8baa    
dask-xgboost              0.1.7           py37_576.g8a31cf5    
(xgb-test) [user1@machine1 machine1_dask]$ conda list | grep py-xgboost-gpu
py-xgboost-gpu            0.90               589.g8a21f75   
(xgb-test) [user1@machine1 machine1_dask]$

(xgb-test) [user1@machine1 machine1_dask]$ conda list | grep distributed
distributed               2.3.2                      py_1
(xgb-test) [user1@machine1 machine1_dask]$

Machine information :- 
uname -r
4.14.0-115.13.1.el7a.ppc64le

GPU information : - 
GPU 0: Tesla V100-SXM2-16GB 
GPU 1: Tesla V100-SXM2-16GB 
GPU 2: Tesla V100-SXM2-16GB 
GPU 3: Tesla V100-SXM2-16GB

```

**Comment by AK-ayush** [comment]
@pradghos you can try with `--memory-limit` in `dask-cuda-cluster` while starting the cuda workers. it is failing because worker is trying to use more RAM than allocated.
Example:
`dask-cuda-worker tcp://<scheduler ip information> --memory-limit 50GB`

**Comment by pradghos** [comment]
> 
> 
> @pradghos you can try with `--memory-limit` in `dask-cuda-cluster` while starting the cuda workers. it is failing because worker is trying to use more RAM than allocated.
> Example:
> `dask-cuda-worker tcp://<scheduler ip information> --memory-limit 50GB`

I have tried `dask-cuda-worker tcp://<scheduler ip information> --memory-limit 50GB` and no more hitting the issue - @AK-ayush - Thank you for the suggestion !
