### ISSUE TITLE
LocalCUDACluster fails with any UCX options other than `protocol='ucx`

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/dask-cuda#251]
I'm encountering this currently when trying to test with Dask and Distributed 2.11 (master for both). 

Trying to enable any of the following options on `LocalCUDACluster` fails with the exception below:
```
    enable_tcp_over_ucx = True
    enable_nvlink = True
    enable_infiniband = False
```

```
  File "test.py", line 407, in <module>
    cluster = LocalCUDACluster(protocol="ucx", enable_nvlink=True)
  File "/home/nfs/cnolet/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py", line 241, in __init__
    **kwargs,
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/local.py", line 211, in __init__
    security=security,
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/spec.py", line 256, in __init__
    self.sync(self._start)
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/cluster.py", line 161, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/nfs/cnolet/workspace/distributed/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/home/nfs/cnolet/workspace/distributed/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/home/nfs/cnolet/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/spec.py", line 284, in _start
    self.scheduler = await self.scheduler
  File "/home/nfs/cnolet/workspace/distributed/distributed/scheduler.py", line 1414, in start
    await self.listen(addr, listen_args=self.listen_args)
  File "/home/nfs/cnolet/workspace/distributed/distributed/core.py", line 321, in listen
    await listener.start()
  File "/home/nfs/cnolet/workspace/distributed/distributed/comm/ucx.py", line 286, in start
    init_once()
  File "/home/nfs/cnolet/workspace/distributed/distributed/comm/ucx.py", line 48, in init_once
    ucx_config = _scrub_ucx_config()
  File "/home/nfs/cnolet/workspace/distributed/distributed/comm/ucx.py", line 365, in _scrub_ucx_config
    dask.config.get("ucx.tcp"),
  File "/home/nfs/cnolet/workspace/dask/dask/config.py", line 454, in get
    result = result[k]
KeyError: 'tcp'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/nfs/cnolet/workspace/distributed/distributed/utils.py", line 200, in ignoring
    yield
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/spec.py", line 607, in close_clusters
    cluster.close(timeout=10)
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/cluster.py", line 82, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/cluster.py", line 161, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/nfs/cnolet/workspace/distributed/distributed/utils.py", line 348, in sync
    raise exc.with_traceback(tb)
  File "/home/nfs/cnolet/workspace/distributed/distributed/utils.py", line 332, in f
    result[0] = yield future
  File "/home/nfs/cnolet/miniconda3/envs/cuml_dev/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/nfs/cnolet/workspace/distributed/distributed/deploy/spec.py", line 386, in _close
    await self.scheduler_comm.close(close_workers=True)
AttributeError: 'NoneType' object has no attribute 'close'
```
Here's my conda environment:
```
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
arrow-cpp                 0.15.0           py37h090bef1_2    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
bokeh                     1.4.0                    py37_0    conda-forge
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
brotli                    1.0.7             he1b5a44_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
cmake                     3.14.5               hf94ab9c_0    conda-forge
cryptography              2.8              py37h72c5cf5_1    conda-forge
cudatoolkit               10.1.243             h6bb024c_0    nvidia
cudf                      0.13.0a200304         py37_3131    rapidsai-nightly
cudnn                     7.6.0                cuda10.1_0    nvidia
cuml                      0.13.0a0+271.g07193d4          pypi_0    pypi
cupy                      7.1.1            py37h0c141eb_1    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
cython                    0.29.15          py37he1b5a44_0    conda-forge
cytoolz                   0.10.1           py37h516909a_0    conda-forge
dask                      2.11.0+17.g2b7945ed           dev_0    <develop>
dask-cuda                 0.13.0b200302           py37_31    rapidsai-nightly
dask-cudf                 0.13.0a200304         py37_3131    rapidsai-nightly
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.11.0+21.g9b5bf448           dev_0    <develop>
dlpack                    0.2                  he1b5a44_1    conda-forge
double-conversion         3.1.5                he1b5a44_2    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
faiss                     1.5.3                    pypi_0    pypi
faiss-gpu                 1.6.1                    pypi_0    pypi
fastavro                  0.22.9           py37h516909a_0    conda-forge
fastrlock                 0.4             py37he1b5a44_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
glog                      0.4.0                he1b5a44_1    conda-forge
gpumap                    0.1.1                    pypi_0    pypi
grpc-cpp                  1.23.0               h18db393_0    conda-forge
gspread                   3.1.0                      py_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httplib2                  0.17.0                   py37_0    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.8                   py37_1000    conda-forge
importlib_metadata        1.5.0                    py37_0    conda-forge
intel-openmp              2020.0                      166
ipykernel                 5.1.4            py37h5ca1d4c_0    conda-forge
ipython                   7.12.0           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.16.0                   py37_0    conda-forge
jinja2                    2.11.1                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json5                     0.9.0                      py_0    conda-forge
jsonschema                3.2.0                    py37_0    conda-forge
jupyter_client            5.3.4                    py37_1    conda-forge
jupyter_core              4.6.2                    py37_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.33.1               h53a641e_8    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libclang                  8.0.0                h6bb024c_0    rapidsai
libcudf                   0.13.0a200304     cuda10.1_3131    rapidsai-nightly
libcumlprims              0.13.0a200212        cuda10.1_9    rapidsai-nightly
libcurl                   7.68.0               hda55be3_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libhwloc                  2.1.0                h3c4fd83_0    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libllvm8                  8.0.1                hc9558a2_0    conda-forge
libnvstrings              0.13.0a200212     cuda10.1_1692    rapidsai-nightly
libopenblas               0.3.7                h5ec1e0e_6    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libprotobuf               3.8.0                h8b12597_0    conda-forge
librmm                    0.13.0a200212      cuda10.1_165    rapidsai-nightly
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hfc65ed5_0    conda-forge
libuv                     1.34.0               h516909a_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
llvmlite                  0.31.0           py37h8b12597_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
markupsafe                1.1.1            py37h516909a_0    conda-forge
mistune                   0.8.4           py37h516909a_1000    conda-forge
mkl                       2020.0                      166
more-itertools            8.2.0                      py_0    conda-forge
msgpack-python            0.6.2            py37hc9558a2_0    conda-forge
nbconvert                 5.6.1                    py37_0    conda-forge
nbformat                  5.0.4                      py_0    conda-forge
nccl                      2.4.6.1              cuda10.1_0    nvidia
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.3                    py37_0    conda-forge
numba                     0.48.0           py37hb3f55d8_0    conda-forge
numpy                     1.18.1           py37h95a1406_0    conda-forge
nvstrings                 0.13.0a200212         py37_1692    rapidsai-nightly
oauth2client              4.1.3                      py_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.7                he1df0ab_6    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1d               h516909a_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    0.25.3           py37hb3f55d8_0    conda-forge
pandoc                    2.9.1.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.6.1                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pexpect                   4.8.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    7.0.0            py37hefe7db6_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.3                      py_0    conda-forge
protobuf                  3.8.0            py37he1b5a44_2    conda-forge
psutil                    5.6.7            py37h516909a_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.1                      py_0    conda-forge
pyarrow                   0.15.0           py37h8b68381_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pynvml                    8.0.4                      py_0    conda-forge
pyopenssl                 19.1.0                   py37_0    conda-forge
pyparsing                 2.4.6                      py_0    conda-forge
pyrsistent                0.15.7           py37h516909a_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
pytest                    5.3.5                    py37_1    conda-forge
python                    3.7.6                h357f687_2    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-mnist              0.6                      pypi_0    pypi
pytz                      2019.3                     py_0    conda-forge
pyyaml                    5.3              py37h516909a_0    conda-forge
pyzmq                     18.1.1           py37h1768529_0    conda-forge
re2                       2020.01.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
rmm                       0.13.0a200212          py37_165    rapidsai-nightly
rsa                       4.0                        py_0    conda-forge
scikit-learn              0.22.1           py37hcdab131_1    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                45.2.0                   py37_0    conda-forge
six                       1.14.0                   py37_0    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.11.0           py37h516909a_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py37_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.12.0            hf3afdfd_1004    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h516909a_3    conda-forge
traitlets                 4.3.3                    py37_0    conda-forge
ucx                       1.7.0+g9d06c3a       cuda10.1_0    rapidsai
ucx-py                    0.13.0a200212+g9d06c3a         py37_32    rapidsai-nightly
umap-learn                0.3.10                   py37_1    conda-forge
uriparser                 0.9.3                he1b5a44_1    conda-forge
urllib3                   1.25.7                   py37_0    conda-forge
wcwidth                   0.1.8                      py_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      2.2.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.3                h3b9ef0a_0    conda-forge
```

**Comment by quasiben** [comment]
this might be because of a recent config change.  if you having changed `~/.config/dask/dask.yaml` can you remove that file and try again ?

**Comment by cjnolet** [comment]
@quasiben, I just removed `~/.config/dask/` but it doesn't appear to have fixed the problem. I also had a `~/.dask/` folder sitting around, which I've removed as well.

**Comment by quasiben** [comment]
We did just merge a fix for this issue.  It looks like you have:
> dask-cuda                 0.13.0b200302           py37_31    rapidsai-nightly

Latest in on anaconda.org is:
> dask-cuda-0.13.0b200304-py37_65.tar.bz2

Can you try upgrading dask-cuda ?

**Comment by cjnolet** [comment]
Indeed, that did work. Thanks @quasiben!
