### ISSUE TITLE
protocol='ucx' failing w/ UCXError('Invalid Parameter') in cuML CI on Centos7

### ISSUE THREAD

**Issue by cjnolet** [rapidsai/dask-cuda#312]
Getting some strange errors from UCX in our Centos7 CI on cuML:

```
ERROR    asyncio:base_events.py:1615 Task exception was never retrieved
future: <Task finished coro=<_listener_handler() done, defined at /share/software/miniconda3/envs/cuml_015_060820/lib/python3.7/site-packages/ucp/core.py:142> exception=UCXError('Invalid parameter')>
Traceback (most recent call last):
  File "/share/software/miniconda3/envs/cuml_015_060820/lib/python3.7/site-packages/ucp/core.py", line 154, in _listener_handler
    conn_request, endpoint_error_handling
  File "ucp/_libs/ucx_api.pyx", line 374, in ucp._libs.ucx_api.UCXWorker.ep_create_from_conn_request
  File "ucp/_libs/ucx_api.pyx", line 56, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Invalid parameter
```

I was able to reproduce this on my own Centos7 workstation. 

We initialize our UCX cluster like this:

```python 
    enable_tcp_over_ucx = True
    enable_nvlink = False
    enable_infiniband = False
    initialize.initialize(create_cuda_context=True,
                          enable_tcp_over_ucx=enable_tcp_over_ucx,
                          enable_nvlink=enable_nvlink,
                          enable_infiniband=enable_infiniband)
    cluster = LocalCUDACluster(protocol="ucx",
                               enable_tcp_over_ucx=enable_tcp_over_ucx,
                               enable_nvlink=enable_nvlink,
                               enable_infiniband=enable_infiniband)
```

It doesn't seem to happen on Ubuntu. I'm not even sure where to start here but I can certianly help dig in further if anyone has any ideas. This seems to have started suddenly.

**Comment by quasiben** [comment]
Thanks @cjnolet -- we think https://github.com/rapidsai/ucx-py/pull/544 should resolve the issue.  After conda packages are uploaded can you test again?

**Comment by cjnolet** [comment]
Absolutely, I will try again. Thanks @quasiben

**Comment by pentschev** [comment]
FWIW, we had also errors in dask-cuda's CI that have now been fixed by https://github.com/rapidsai/ucx-py/pull/544 .

**Comment by cjnolet** [comment]
@pentschev @quasiben I verified this issue has been fixed. Thank you!

**Comment by quasiben** [comment]
Thanks @cjnolet !
