### ISSUE TITLE
Disabling encryption

### ISSUE THREAD

**Issue by benjha** [rapidsai/dask-cuda#352]
Hi @jakirkham,

We are trying Rapids 0.14 on Summit. It turns out, dask-cuda-worker requires encryption now.  How can be disabled ?

In particular, after launching the scheduler:

```
 $dask-scheduler --interface ib0 --scheduler-file $MEMBERWORK/$PROJ_ID/dask/my-scheduler-gpu.json --protocol=tcp
distributed.nanny - INFO -         Start Nanny at: 'tcp://10.41.0.33:44903'
distributed.worker - INFO -       Start worker at:     tcp://10.41.0.33:43983
distributed.worker - INFO -          Listening to:     tcp://10.41.0.33:43983
distributed.worker - INFO -          dashboard at:           10.41.0.33:33001
distributed.worker - INFO - Waiting to connect to:      tcp://10.41.0.32:8786
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -               Threads:                          1
distributed.worker - INFO -                Memory:                   85.00 GB
distributed.worker - INFO -       Local Directory: /gpfs/alpine/stf011/world-shared/benjha/gtc_2020/dask_cupy/svd_perf_eval/rapids_0.11/dask-worker-space/worker-gj0lb1jc
distributed.worker - INFO - -------------------------------------------------
distributed.worker - INFO -         Registered to:      tcp://10.41.0.32:8786
distributed.worker - INFO - -------------------------------------------------
distributed.core - INFO - Starting established connection
```

and launch the dask-cuda-worker, I got the next error:

```
$ dask-cuda-worker --scheduler-file $MEMBERWORK/$PROJ_ID/dask/my-scheduler-gpu.json  --nthreads 1 --memory-limit 85GB --device-memory-limit 16GB  --death-timeout 180 --interface ib0 --enable-nvlink
Traceback (most recent call last):
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/bin/dask-cuda-worker", line 8, in <module>
    sys.exit(go())
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 384, in go
    main()
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 375, in main
    loop.run_sync(run)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/tornado/ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/dask_cuda/dask_cuda_worker.py", line 369, in run
    yield nannies
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/tornado/gen.py", line 501, in callback
    result_list.append(f.result())
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/core.py", line 290, in _
    await self.start()
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/nanny.py", line 273, in start
    start_address, **self.security.get_listen_args("worker")
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/core.py", line 420, in listen
    **kwargs,
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/comm/core.py", line 272, in listen
    return backend.get_listener(loc, handle_comm, deserialize, **kwargs)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 521, in get_listener
    return self._listener_class(loc, handle_comm, deserialize, **connection_args)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 393, in __init__
    self._check_encryption(address, connection_args)
  File "/gpfs/alpine/world-shared/stf011/nvrapids_0.14_gcc_7.4.0/lib/python3.7/site-packages/distributed/comm/tcp.py", line 328, in _check_encryption
    "refusing communication from/to %r" % (self.prefix + address,)
RuntimeError: encryption required by Dask configuration, refusing communication from/to 'tcp://10.41.0.33:0'
```
dask-workers are working as usual, i.e. no encryption required.  @ssomnath @jqyin

Thanks,

**Comment by jakirkham** [comment]
Will need to update `dask-cuda` to `0.14.1` so we get the fix in PR ( https://github.com/rapidsai/dask-cuda/pull/321 ).

cc @pentschev (in case there is anything else I'm missing)

**Comment by pentschev** [comment]
Thanks @jakirkham , I think your suggestion should be enough. It seems that this has indeed resolved the issue, as per what I read on Slack, could you confirm it @benjha ?

**Comment by benjha** [comment]
Yes, it worked with Dask-cuda 0.14.1

Thanks

**Comment by jakirkham** [comment]
Cool, going to go ahead and close, but please let us know if other things need to be addressed and we can reopen.
