### ISSUE TITLE
[BUG] Can't create LocalCUDACluster with 0.16 conda nightlies

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#355]
```
rgelhausen@rl-dgx2-d17-u16-rapids-dgx202:~$ conda list | grep rapids
cudf                      0.16.0a200811   py37_gf9c85dd45_231    rapidsai-nightly
cuspatial                 0.16.0a200811   py37_g2b6c1d1_0    rapidsai-nightly
dask-cuda                 0.16.0a200811            py37_5    rapidsai-nightly
dask-cudf                 0.16.0a200811   py37_gf9c85dd45_231    rapidsai-nightly
libcudf                   0.16.0a200811   cuda10.2_gf9c85dd45_231    rapidsai-nightly
libcuspatial              0.16.0a200811   cuda10.2_g2b6c1d1_0    rapidsai-nightly
librmm                    0.16.0a200811   cuda10.2_g1b25853_109    rapidsai-nightly
numba                     0.51.0dev.rapidsai0.15  py37h0da4684_0    rapidsai-nightly
rmm                       0.16.0a200811   py37_g1b25853_109    rapidsai-nightly
ucx                       1.8.1+g6b29558       cuda10.2_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.16.0a200811+g6b29558         py37_22    rapidsai-nightly
```
Dask versions:
```
(taxi) rgelhausen@rl-dgx2-d17-u16-rapids-dgx202:~$ conda list | grep distributed
distributed               2.22.0+17.g25d5a334          pypi_0    pypi
(taxi) rgelhausen@rl-dgx2-d17-u16-rapids-dgx202:~$ conda list | grep dask
dask                      2.22.0+9.g14c53510          pypi_0    pypi
```

```
(taxi) rgelhausen@rl-dgx2-d17-u16-rapids-dgx202:~$ python
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dask_cuda import LocalCUDACluster
>>> cluster = LocalCUDACluster()
```
Repeating stacktrace:
```
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):                                                                                         
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker                                                                                                            
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/core.py", line 305, in _
    await self.start()                                    
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/worker.py", line 1094, in start
    await self._register_with_scheduler()
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/worker.py", line 815, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/worker.py", line 815, in <dictcomp>       
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/_collections_abc.py", line 744, in __iter__                          
    yield (key, self._mapping[key])                                           
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/dask_cuda/device_host_file.py", line 141, in __getitem__
    return self.host_buffer[key]                                                                                                                                      
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/zict/buffer.py", line 78, in __getitem__                                                         
    return self.slow_to_fast(key)                                
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/zict/buffer.py", line 65, in slow_to_fast
    value = self.slow[key]                                                                                         
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/zict/func.py", line 38, in __getitem__
    return self.load(self.d[key])                                                                                           
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 539, in deserialize_bytes
    frames = merge_frames(header, frames)                                                                        
  File "/home/rgelhausen/conda/envs/taxi/lib/python3.7/site-packages/distributed/protocol/utils.py", line 54, in merge_frames
    writeables = list(header["writeable"])                                                                                
KeyError: 'writeable'                                    
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:59506 remote=tcp://127.0.0.1:41631>
distributed.nanny - ERROR - Failed while trying to start worker process: 'writeable'
```

**Comment by pentschev** [comment]
cc @jakirkham seems related to https://github.com/dask/distributed/pull/4004 and https://github.com/dask/distributed/pull/4016 .

**Comment by randerzander** [comment]
for what it's worth, I have the same problem with the latest 0.15 nightlies (also with dask & distributed master)

**Comment by jakirkham** [comment]
Hmm...I'm having trouble reproducing this.

```python
In [1]: import dask_cuda

In [2]: cluster = dask_cuda.LocalCUDACluster()

In [3]: cluster
Out[3]: LocalCUDACluster('tcp://127.0.0.1:40661', workers=8, threads=8, memory=1.08 TB)
```

Is there something else I'm missing here?

**Comment by randerzander** [comment]
Hmm.. looks like this was a temporary problem with my machine. I can no longer reproduce with the same conda environment.

Thanks!

**Comment by jakirkham** [comment]
Thanks for checking. If it crops back up, please let us know 🙂

**Comment by rilango** [comment]
I am seeing something similar with Rapids 0.16.

distributed.nanny - ERROR - Failed while trying to start worker process: 
distributed.nanny - ERROR - Failed while trying to start worker process: 
Task exception was never retrieved
future: <Task finished name='Task-44' coro=<_wrap_awaitable() done, defined at /opt/conda/envs/rapids/lib/python3.8/asyncio/tasks.py:685> exception=AssertionError()>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 1091, in start
    await self._register_with_scheduler()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 812, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 812, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/opt/conda/envs/rapids/lib/python3.8/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cuda-0+untagged.1.g0577fba-py3.8.egg/dask_cuda/device_host_file.py", line 141, in __getitem__
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py", line 78, in __getitem__
    return self.slow_to_fast(key)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py", line 65, in slow_to_fast
    value = self.slow[key]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/func.py", line 38, in __getitem__
    return self.load(self.d[key])
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 534, in deserialize_bytes
    frames = merge_frames(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/utils.py", line 51, in merge_frames
    assert sum(lengths) == sum(map(nbytes, frames))
AssertionError
Task exception was never retrieved
future: <Task finished name='Task-43' coro=<_wrap_awaitable() done, defined at /opt/conda/envs/rapids/lib/python3.8/asyncio/tasks.py:685> exception=AssertionError()>
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.8/asyncio/tasks.py", line 692, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 305, in _
    await self.start()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 1091, in start
    await self._register_with_scheduler()
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 812, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 812, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/opt/conda/envs/rapids/lib/python3.8/_collections_abc.py", line 744, in __iter__
    yield (key, self._mapping[key])
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cuda-0+untagged.1.g0577fba-py3.8.egg/dask_cuda/device_host_file.py", line 141, in __getitem__
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py", line 78, in __getitem__
    return self.slow_to_fast(key)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py", line 65, in slow_to_fast
    value = self.slow[key]
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/func.py", line 38, in __getitem__
    return self.load(self.d[key])
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 534, in deserialize_bytes
    frames = merge_frames(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/utils.py", line 51, in merge_frames
    assert sum(lengths) == sum(map(nbytes, frames))
AssertionError
distributed.nanny - ERROR - Failed while trying to start worker process: 
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-2d9247d7ce9b> in <module>
     56                       enable_infiniband=enable_infiniband)
     57 print('Initialized')
---> 58 cluster = LocalCUDACluster(protocol="ucx",
     59                            CUDA_VISIBLE_DEVICES=[0, 1],
     60                            enable_tcp_over_ucx=enable_tcp_over_ucx,

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cuda-0+untagged.1.g0577fba-py3.8.egg/dask_cuda/local_cuda_cluster.py in __init__(self, n_workers, threads_per_worker, processes, memory_limit, device_memory_limit, CUDA_VISIBLE_DEVICES, data, local_directory, protocol, enable_tcp_over_ucx, enable_infiniband, enable_nvlink, enable_rdmacm, ucx_net_devices, rmm_pool_size, rmm_managed_memory, **kwargs)
    269         self.cuda_visible_devices = CUDA_VISIBLE_DEVICES
    270         self.scale(n_workers)
--> 271         self.sync(self._correct_state)
    272 
    273     def new_worker_spec(self):

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/deploy/cluster.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    181             return future
    182         else:
--> 183             return sync(self.loop, func, *args, **kwargs)
    184 
    185     def _log(self, log):

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

/opt/conda/envs/rapids/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/deploy/spec.py in _correct_state_internal(self)
    353                 for w in workers:
    354                     w._cluster = weakref.ref(self)
--> 355                     await w  # for tornado gen.coroutine support
    356             self.workers.update(dict(zip(to_open, workers)))
    357 

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py in _()
    303                         )
    304                 else:
--> 305                     await self.start()
    306                     self.status = Status.running
    307             return self

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py in start(self)
    293 
    294         logger.info("        Start Nanny at: %r", self.address)
--> 295         response = await self.instantiate()
    296         if response == Status.running:
    297             assert self.worker_address

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py in instantiate(self, comm)
    376 
    377         else:
--> 378             result = await self.process.start()
    379         return result
    380 

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py in start(self)
    579             return
    580 
--> 581         msg = await self._wait_until_connected(uid)
    582         if not msg:
    583             return self.status

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py in _wait_until_connected(self, uid)
    694                 )
    695                 await self.process.join()
--> 696                 raise msg["exception"]
    697             else:
    698                 return msg

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/nanny.py in run()
    764             """
    765             try:
--> 766                 await worker
    767             except Exception as e:
    768                 logger.exception("Failed to start worker")

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py in _()
    303                         )
    304                 else:
--> 305                     await self.start()
    306                     self.status = Status.running
    307             return self

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py in start()
   1089         self._pending_plugins = ()
   1090 
-> 1091         await self._register_with_scheduler()
   1092 
   1093         self.start_periodic_callbacks()

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py in _register_with_scheduler()
    810                         name=self.name,
    811                         nbytes=self.nbytes,
--> 812                         types={k: typename(v) for k, v in self.data.items()},
    813                         now=time(),
    814                         resources=self.total_resources,

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py in <dictcomp>()
    810                         name=self.name,
    811                         nbytes=self.nbytes,
--> 812                         types={k: typename(v) for k, v in self.data.items()},
    813                         now=time(),
    814                         resources=self.total_resources,

/opt/conda/envs/rapids/lib/python3.8/_collections_abc.py in __iter__()
    742     def __iter__(self):
    743         for key in self._mapping:
--> 744             yield (key, self._mapping[key])
    745 
    746 ItemsView.register(dict_items)

/opt/conda/envs/rapids/lib/python3.8/site-packages/dask_cuda-0+untagged.1.g0577fba-py3.8.egg/dask_cuda/device_host_file.py in __getitem__()

/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py in __getitem__()
     76             return self.fast[key]
     77         elif key in self.slow:
---> 78             return self.slow_to_fast(key)
     79         else:
     80             raise KeyError(key)

/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/buffer.py in slow_to_fast()
     63 
     64     def slow_to_fast(self, key):
---> 65         value = self.slow[key]
     66         # Avoid useless movement for heavy values
     67         if self.weight(key, value) <= self.n:

/opt/conda/envs/rapids/lib/python3.8/site-packages/zict/func.py in __getitem__()
     36 
     37     def __getitem__(self, key):
---> 38         return self.load(self.d[key])
     39 
     40     def __setitem__(self, key, value):

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/serialize.py in deserialize_bytes()
    532         header = {}
    533     frames = decompress(header, frames)
--> 534     frames = merge_frames(header, frames)
    535     return deserialize(header, frames)
    536 

/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/protocol/utils.py in merge_frames()
     49 
     50     assert len(lengths) == len(writeables)
---> 51     assert sum(lengths) == sum(map(nbytes, frames))
     52 
     53     if all(len(f) == l for f, l in zip(frames, lengths)):

AssertionError:

**Comment by pentschev** [comment]
Before anything else, could you try cleaning temporary directories? `dask-worker-space` and `storage` can be particularly problematic. Better yet would be to switch to an empty directory to avoid any other garbage that may exist.

If that doesn't work, could you post a MRE and the output of `conda list` ?

**Comment by rilango** [comment]
@pentschev starting in a new directory worked.

Thankyou!!!
