### ISSUE TITLE
Having issue running: "cluster = dask_cuda.LocalCUDACluster()" Using Python 3.8.5 on Windows 10, with CUDA 11.1 and latest drives, (2xRTX 3090)

### ISSUE THREAD

**Issue by CallShaul** [rapidsai/dask-cuda#476]
Having issue running: "cluster = dask_cuda.LocalCUDACluster()" Using Python 3.8.5 on Windows 10, with CUDA 11.2 and latest drives, (2xRTX 3090)

Tried copying missing file as mentioned in the Nvidia forum:
https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/295198/nvmldll-and-nvsmi-folder-missing/

Now getting this error:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 150, in get_n_gpus
    return len(os.environ["CUDA_VISIBLE_DEVICES"].split(","))
  File "C:\ProgramData\Anaconda3\lib\os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'CUDA_VISIBLE_DEVICES'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\toolz\functoolz.py", line 456, in memof
    return cache[k]
KeyError: ()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-0e41b44ee01c>", line 1, in <module>
    cluster = dask_cuda.LocalCUDACluster()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\local_cuda_cluster.py", line 151, in __init__
    CUDA_VISIBLE_DEVICES = cuda_visible_devices(0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 442, in cuda_visible_devices
    visible = range(get_n_gpus())
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 152, in get_n_gpus
    return get_gpu_count()
  File "C:\ProgramData\Anaconda3\lib\site-packages\toolz\functoolz.py", line 460, in memof
    cache[k] = result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dask_cuda\utils.py", line 102, in get_gpu_count
    pynvml.nvmlInit()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 749, in nvmlInit
    check_return(ret)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pynvml\nvml.py", line 366, in check_return
    raise NVMLError(ret)
pynvml.nvml.NVMLError_Uninitialized: Uninitialized

running nvidia-smi yields:

![image](https://user-images.githubusercontent.com/52006780/102014643-ad15b300-3d5f-11eb-8394-9c12fd3cb2e6.png)

_Originally posted by @CallShaul in https://github.com/rapidsai/dask-cuda/issues/122#issuecomment-744015304_

**Comment by quasiben** [comment]
Unfortunately, RAPIDS is not supported on Windows.  You could try with WSL -- there is some discussion about folks doing that in the main RAPIDS repo:
https://github.com/rapidsai/cudf/issues/28

**Comment by quasiben** [comment]
@CallShaul there is a blog post on running RAPIDS on WSL:
https://andradaolteanu.medium.com/how-to-install-and-use-rapids-on-your-windows-workstation-a31af966ef62

If you have time and interest going through that post would be great!

**Comment by quasiben** [comment]
Another blog post was posted today as well:
https://medium.com/rapids-ai/running-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux-c5cbb2c56e04

**Comment by pentschev** [comment]
This has been inactive without follow-ups from author, closing.
