### ISSUE TITLE
Runing multi-GPU with Dask failed: n_uniques == world

### ISSUE THREAD

**Issue by xuanqing94** [rapidsai/dask-cuda#478]
I posted this [issue](https://github.com/dmlc/xgboost/issues/6539) to xgboost but later I think it is more like the problem rooting from dask-cuda so I copy it here.

I am using the latest stable release of xgboost (1.3.0), dask(2020.12.0) and dask_cuda(0.17.0). Both installed from pypi.

hardwares include 2x2070 GPUs.

I ran the official example(https://github.com/dmlc/xgboost/blob/master/demo/dask/gpu_training.py) on my little server but unfortunately, it raises the following error:

Traceback (most recent call last):
File "sklearn_gpu_training.py", line 42, in
main(client)
File "sklearn_gpu_training.py", line 25, in main
regressor.fit(X, y, eval_set=[(X, y)])
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/core.py", line 421, in inner_f
return f(**kwargs)
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/dask.py", line 1118, in fit
return self.client.sync(self._fit_async,
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/distributed/client.py", line 831, in sync
return sync(
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/distributed/utils.py", line 340, in sync
raise exc.with_traceback(tb)
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/distributed/utils.py", line 324, in f
result[0] = yield future
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
value = future.result()
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/dask.py", line 1093, in _fit_async
results = await train(client=self.client,
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/dask.py", line 701, in _train_async
results = await client.gather(futures)
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/distributed/client.py", line 1850, in _gather
raise exception.with_traceback(traceback)
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/dask.py", line 668, in dispatched_train
bst = worker_train(params=local_param,
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/training.py", line 219, in train
bst = _train_internal(params, dtrain,
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/training.py", line 114, in _train_internal
bst.update(dtrain, i, obj)
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/core.py", line 1267, in update
_check_call(_LIB.XGBoosterUpdateOneIter(self.handle,
File "/home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/core.py", line 188, in _check_call
raise XGBoostError(py_str(_LIB.XGBGetLastError()))
xgboost.core.XGBoostError: [07:22:46] ../src/tree/updater_gpu_hist.cu:786: Exception in gpu_hist: [07:22:46] ../src/common/device_helpers.cu:64: Check failed: n_uniques == world (1 vs. 2) : Multiple processes within communication group running on same CUDA device is not supported
Stack trace:
[bt] (0) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x304fd5) [0x7f7754fb5fd5]
[bt] (1) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x49de04) [0x7f775514ee04]
[bt] (2) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x178a55) [0x7f7754e29a55]
[bt] (3) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x17a6a7) [0x7f7754e2b6a7]
[bt] (4) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(+0x1a2d59) [0x7f7754e53d59]
[bt] (5) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/site-packages/xgboost/lib/libxgboost.so(XGBoosterUpdateOneIter+0x58) [0x7f7754d310c8]
[bt] (6) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/lib-dynload/../../libffi.so.7(+0x69dd) [0x7f780a0039dd]
[bt] (7) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/lib-dynload/../../libffi.so.7(+0x6067) [0x7f780a003067]
[bt] (8) /home/xqliu/miniconda3/envs/system-dev/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so(+0x10da8) [0x7f780a019da8]

**Comment by xuanqing94** [comment]
Closing this issue. It is fixed in the [original post](https://github.com/dmlc/xgboost/issues/6539).
