### ISSUE TITLE
Multi-GPU - RuntimeError: Set changed size during iteration

### ISSUE THREAD

**Issue by kyoungrok0517** [rapidsai/dask-cuda#482]
Hello. I'm having trouble initialize `LocalCUDACluster` in multi-gpu environment. I'm using two 3090s (NVLink) and see the following error when I run my code.

```
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:54948 remote=tcp://127.0.0.1:45293>
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:54950 remote=tcp://127.0.0.1:45293>
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py:623> exception=RuntimeError('Set changed size during iteration')>
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py:623> exception=RuntimeError('Set changed size during iteration')>
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:54952 remote=tcp://127.0.0.1:45293>
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7fd3274aa510>>, <Task finished coro=<SpecCluster._correct_state_internal() done, defined at /home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/spec.py:320> exception=RuntimeError('Set changed size during iteration')>)
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/spec.py", line 355, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:54956 remote=tcp://127.0.0.1:45293>
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.comm.tcp - WARNING - Closing dangling stream in <TCP  local=tcp://127.0.0.1:54954 remote=tcp://127.0.0.1:45293>
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py:623> exception=RuntimeError('Set changed size during iteration')>
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
Task exception was never retrieved
future: <Task finished coro=<_wrap_awaitable() done, defined at /home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py:623> exception=RuntimeError('Set changed size during iteration')>
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/asyncio/tasks.py", line 630, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed to start worker
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
distributed.nanny - ERROR - Failed while trying to start worker process: Set changed size during iteration
Traceback (most recent call last):
  File "check_multi_gpu.py", line 18, in <module>
    with LocalCUDACluster(n_workers=n_gpu) as cluster:
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/dask_cuda/local_cuda_cluster.py", line 268, in __init__
    self.sync(self._correct_state)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/spec.py", line 355, in _correct_state_internal
    await w  # for tornado gen.coroutine support
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 295, in start
    response = await self.instantiate()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 378, in instantiate
    result = await self.process.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 581, in start
    msg = await self._wait_until_connected(uid)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 696, in _wait_until_connected
    raise msg["exception"]
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/nanny.py", line 766, in run
    await worker
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/core.py", line 301, in _
    await self.start()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 1154, in start
    await self._register_with_scheduler()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in _register_with_scheduler
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/worker.py", line 875, in <dictcomp>
    types={k: typename(v) for k, v in self.data.items()},
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/_collections_abc.py", line 743, in __iter__
    for key in self._mapping:
RuntimeError: Set changed size during iteration
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/spec.py", line 641, in close_clusters
    cluster.close(timeout=10)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 104, in close
    return self.sync(self._close, callback_timeout=timeout)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 183, in sync
    return sync(self.loop, func, *args, **kwargs)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/kyoungrok/anaconda3/envs/sparse/lib/python3.7/site-packages/distributed/deploy/spec.py", line 413, in _close
    assert w.status == Status.closed, w.status
AssertionError: Status.init
```

**Comment by kyoungrok0517** [comment]
I even run the following code for the test, but sees the same error. 

```python
from dask_cuda import LocalCUDACluster
from dask.distributed import Client
import pynvml
import os

def get_device_uuid():
    visible_devices = os.environ.get('CUDA_VISIBLE_DEVICES')
    current_gpu = int(visible_devices.split(',')[0])  # GPU used by this worker process
    pynvml.nvmlInit()
    handle = pynvml.nvmlDeviceGetHandleByIndex(current_gpu)
    return pynvml.nvmlDeviceGetUUID(handle).decode()

if __name__ == '__main__':
    pynvml.nvmlInit()
    n_gpu = pynvml.nvmlDeviceGetCount()
    with LocalCUDACluster(n_workers=n_gpu) as cluster:
        with Client(cluster) as client:
            print(client.run(get_device_uuid))
```

Normally this code should print like this

```
{'tcp://127.0.0.1:34689': 'GPU-f872a0b4-5b88-88ab-5abe-7fe2fc805c87',
'tcp://127.0.0.1:37593': 'GPU-f9def763-5b00-bf42-618b-1e1b58806fbc',
'tcp://127.0.0.1:40621': 'GPU-5b18a4fc-7769-216d-92e9-dec382bedb84',
'tcp://127.0.0.1:41257': 'GPU-998f046b-4e3a-92c9-ffc2-34784e54da8c'}
```

Please refer to this issue.
https://github.com/dmlc/xgboost/issues/6539

**Comment by pentschev** [comment]
Last time I've seen this issue it was due to dangling old files. Could you try running the script from an empty directory? Alternatively you could try passing `local_directory=/some/empty/dir` to `LocalCUDACluster` as well.

For reference, the code above runs fine for me on a clean RAPIDS 0.17 environment.

**Comment by kyoungrok0517** [comment]
> Last time I've seen this issue it was due to dangling old files. Could you try running the script from an empty directory? Alternatively you could try passing `local_directory=/some/empty/dir` to `LocalCUDACluster` as well.
> 
> For reference, the code above runs fine for me on a clean RAPIDS 0.17 environment.

Wow that was true! Then exactly what file should I delete to clean my directory? I'm running dask-cuda in my project repo so emptying every time I run the code is not an option.

**Comment by pentschev** [comment]
This is probably a duplicate of https://github.com/rapidsai/dask-cuda/issues/265 then. Usually deleting those files isn't necessary, it may happen if the cluster didn't terminate correctly for some reason. I believe cleaning `dask-worker-space` and `storage` directories will suffice, I can't remember if there were others as I haven't seen this myself in quite a while. If you want to be on the safe side, I would suggest you use `local_directory` pointing to some temporary directory in your case, that will prevent garbage on your project's directory and allow you to clean up the temporary one without worrying too much about your project.

**Comment by kyoungrok0517** [comment]
I see. Thanks for the guide!
