### ISSUE TITLE
SyntaxError when importing LocalCUDACluster from dask_cuda

### ISSUE THREAD

**Issue by aclifton314** [rapidsai/dask-cuda#606]
System: Red Hat Enterprise Linux Server release 7.7 (Maipo)
CUDA:  10.2
dask-cuda: 0.19.0
python: 3.7.10

I'm getting a SyntaxError whenever I try to import `LocalCUDACluster` from `dask_cuda`:
```python
Traceback (most recent call last):
  File "lcs_dask.py", line 2, in <module>
    from dask_cuda import LocalCUDACluster
  File "/path/to/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cuda/__init__.py", line 5, in <module>
    from .cuda_worker import CUDAWorker
  File "/path/to/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cuda/cuda_worker.py", line 21, in <module>
    from .device_host_file import DeviceHostFile
  File "/path/to/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cuda/device_host_file.py", line 23, in <module>
    from .utils import nvtx_annotate
  File "/path/to/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cuda/utils.py", line 9, in <module>
    import pynvml
  File "/cm/local/apps/cuda/libs/current/pynvml/pynvml.py", line 1671
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(c_count.value)?
```

Any thoughts about what I might be doing wrong?

**Comment by jakirkham** [comment]
Seems like it is picking up some outdated version of `pynvml` from outside the environment. Could you please try running `conda install -c rapidsai -c conda-forge pynvml` and then retry?

**Comment by aclifton314** [comment]
@jakirkham Thank you for the prompt reply!
I tried running `conda install -c rapidsai -c conda-forge pynvml` but got the following:
```python
(dask-cudf) $ conda install -c rapidsai -c conda-forge pynvml
Collecting package metadata (current_repodata.json): done
Solving environment: -
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::cudnn==8.1.0.77=h90431f1_0
  - conda-forge/linux-64::cutensor==1.2.2.5=h96e36e3_3
  - conda-forge/linux-64::nccl==2.9.8.1=hdc17891_0
  - conda-forge/linux-64::cupy==8.6.0=py37h3c5eebb_0
  - rapidsai/linux-64::cudf==0.19.2=cuda_11.2_py37_gab3b3f653a_0
done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda

# All requested packages already installed.
```

**Comment by jakirkham** [comment]
What does `conda info` show?

**Comment by aclifton314** [comment]
```python
(dask-cudf) [aclifton@g003 bert_classifier]$ conda info

     active environment : dask-cudf
    active env location : /home/aclifton/anaconda3/envs/dask-cudf
            shell level : 1
       user config file : /home/aclifton/.condarc
 populated config files : /home/aclifton/.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.17
       base environment : /home/aclifton/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aclifton/anaconda3/pkgs
                          /home/aclifton/.conda/pkgs
       envs directories : /home/aclifton/anaconda3/envs
                          /home/aclifton/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Linux/3.10.0-1062.el7.x86_64 rhel/7.7 glibc/2.17
                UID:GID : 1005:1004
             netrc file : None
           offline mode : False
```

**Comment by jakirkham** [comment]
Thanks 🙂

Is `PYTHONPATH` or any other related environment variable being set? Trying to understand why `pynvml` isn't being picked up from the environment

**Comment by aclifton314** [comment]
My pleasure. Yes. `PYTHONPATH` is set:
```python
(dask-cudf) [aclifton@g003 ~]$ echo $PYTHONPATH
/cm/shared/apps/ml-pythondeps-py36-cuda10.1-gcc/lib64/python3.6/site-packages:/cm/shared/apps/tensorflow-py36-cuda10.1-gcc/1.15.3/lib64/python3.6/site-packages/:/cm/shared/apps/tensorflow-py36-cuda10.1-gcc/1.15.3/lib/python3.6/site-packages/:/cm/shared/apps/keras-py36-cuda10.1-gcc/2.3.1/lib64/python3.6/site-packages/:/cm/shared/apps/keras-py36-cuda10.1-gcc/2.3.1/lib/python3.6/site-packages/:/cm/shared/apps/ml-pythondeps-py36-cuda10.1-gcc/safeimport:/cm/local/apps/cuda/libs/current/pynvml:/cm/shared/apps/jupyter/10.1.0/lib64/python3.7/site-packages/:/cm/shared/apps/jupyter/10.1.0/lib/python3.7/site-packages/
```

**Comment by jakirkham** [comment]
For the sake of testing, could you please try unsetting `PYTHONPATH` and retry?

**Comment by aclifton314** [comment]
I unset `PYTHONPATH` and am now getting:
```python
Traceback (most recent call last):
  File "lcs_dask.py", line 4, in <module>
    import dask_cudf
ModuleNotFoundError: No module named 'dask_cudf'
```

**Comment by jakirkham** [comment]
Thanks for checking.

What does `conda list` show?

**Comment by aclifton314** [comment]
```python
(dask-cudf) [aclifton@g003 bert_classifier]$ conda list
# packages in environment at /home/aclifton/anaconda3/envs/dask-cudf:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
abseil-cpp                20210324.1           h9c3ff4c_0    conda-forge
aiohttp                   3.7.4            py37h5e8e339_0    conda-forge
arrow-cpp                 1.0.1           py37hb133d9b_39_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
aws-c-cal                 0.5.7                h3622835_1    conda-forge
aws-c-common              0.5.11               h7f98852_0    conda-forge
aws-c-event-stream        0.2.7                h5011166_5    conda-forge
aws-c-io                  0.9.12               h3dd054d_1    conda-forge
aws-checksums             0.1.11               hc0e0e8b_6    conda-forge
aws-sdk-cpp               1.8.186              h9ad65fb_2    conda-forge
bokeh                     2.3.2            py37h89c1867_0    conda-forge
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.17.72            pyhd8ed1ab_0    conda-forge
botocore                  1.20.72            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1001    conda-forge
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cachetools                4.2.2              pyhd8ed1ab_0    conda-forge
catalogue                 2.0.4            py37h89c1867_0    conda-forge
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.5           py37hc58025e_0    conda-forge
chardet                   4.0.0            py37h89c1867_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py37h5d9358c_0    conda-forge
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
cudf                      0.19.2          cuda_11.2_py37_gab3b3f653a_0    rapidsai
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cupy                      8.6.0            py37h3c5eebb_0    conda-forge
cutensor                  1.2.2.5              h96e36e3_3    conda-forge
cymem                     2.0.5            py37hcd2ae1e_1    conda-forge
cython-blis               0.7.4            py37h902c9e0_0    conda-forge
cytoolz                   0.11.0           py37h5e8e339_3    conda-forge
dask                      2021.4.0           pyhd8ed1ab_0    conda-forge
dask-core                 2021.4.0           pyhd3eb1b0_0    defaults
dask-cuda                 0.19.0                   py37_0    rapidsai
dataclasses               0.8                pyhc8e2a94_1    conda-forge
distributed               2021.4.0         py37h06a4308_0    defaults
dlpack                    0.3                  he1b5a44_1    conda-forge
fastavro                  1.4.0            py37h5e8e339_0    conda-forge
fastrlock                 0.6              py37hcd2ae1e_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
fsspec                    2021.4.0           pyhd8ed1ab_0    conda-forge
gflags                    2.2.2             he1b5a44_1004    conda-forge
glog                      0.5.0                h48cff8f_0    conda-forge
google-api-core           1.26.3             pyhd8ed1ab_0    conda-forge
google-auth               1.30.0             pyh44b312d_0    conda-forge
google-cloud-core         1.5.0              pyhd3deb0d_0    conda-forge
google-cloud-storage      1.19.0                     py_0    conda-forge
google-crc32c             1.1.2            py37hab72019_0    conda-forge
google-resumable-media    1.2.0              pyhd3deb0d_0    conda-forge
googleapis-common-protos  1.53.0           py37h89c1867_0    conda-forge
grpc-cpp                  1.37.1               h2519f57_2    conda-forge
grpcio                    1.37.1           py37hb27c1af_0    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    3.0.0              pyhd8ed1ab_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libcrc32c                 1.1.1                h9c3ff4c_2    conda-forge
libcudf                   0.19.2          cuda11.2_gab3b3f653a_0    rapidsai
libcurl                   7.76.1               hc4aaa36_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.16.0               h780b84a_0    conda-forge
librmm                    0.19.0          cuda11.2_g7065af3_0    rapidsai
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libthrift                 0.14.1               he6d91bd_1    conda-forge
libtiff                   4.2.0                hdc55705_1    conda-forge
libutf8proc               2.6.1                h7f98852_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
llvmlite                  0.36.0           py37hf484d3e_0    numba
locket                    0.2.0                      py_2    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                2.0.0            py37h5e8e339_0    conda-forge
msgpack-python            1.0.2            py37h2527ec5_1    conda-forge
multidict                 5.1.0            py37h5e8e339_1    conda-forge
murmurhash                1.0.5            py37hcd2ae1e_0    conda-forge
nccl                      2.9.8.1              hdc17891_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
numba                     0.53.1          np1.11py3.7h04863e7_g97fe221b3_0    numba
numpy                     1.20.2           py37h038b26d_0    conda-forge
nvtx                      0.2.3            py37h5e8e339_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hf7af979_0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
orc                       1.6.7                h89a63ab_2    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.4            py37h219a48f_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathy                     0.5.2              pyhd8ed1ab_0    conda-forge
pillow                    8.1.2            py37h4600e1f_1    conda-forge
pip                       21.1.1             pyhd8ed1ab_0    conda-forge
preshed                   3.0.5            py37hcd2ae1e_0    conda-forge
protobuf                  3.16.0           py37hcd2ae1e_0    conda-forge
psutil                    5.8.0            py37h5e8e339_1    conda-forge
pyarrow                   1.0.1           py37hb63ea2f_39_cuda    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydantic                  1.7.3            py37h5e8e339_1    conda-forge
pynvml                    8.0.4                      py_1    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py37h5e8e339_0    conda-forge
re2                       2021.04.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rmm                       0.19.0          cuda_11.2_py37_g7065af3_0    rapidsai
rsa                       4.7.2              pyh44b312d_0    conda-forge
s2n                       1.0.7                h9b69904_0    conda-forge
s3transfer                0.4.2              pyhd8ed1ab_0    conda-forge
setuptools                49.6.0           py37h89c1867_3    conda-forge
shellingham               1.4.0              pyh44b312d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smart_open                2.2.1              pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
spacy                     3.0.6            py37hda21425_0    conda-forge
spacy-legacy              3.0.5              pyhd8ed1ab_0    conda-forge
spdlog                    1.7.0                hc9558a2_2    conda-forge
sqlite                    3.35.5               h74cdb3f_0    conda-forge
srsly                     2.4.1            py37hcd2ae1e_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
thinc                     8.0.3            py37hda21425_1    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37h5e8e339_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
typer                     0.3.2              pyhd8ed1ab_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wasabi                    0.8.2              pyh44b312d_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py37h5e8e339_1    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

**Comment by jakirkham** [comment]
It appears `dask-cudf` is not installed (hence the `ImportError`). Can you please install that too?

**Comment by aclifton314** [comment]
Is `conda install dask-cudf` sufficient?

**Comment by jakirkham** [comment]
Would need to include the `rapidsai` and `conda-forge` channels (unless they are in `.condarc`)

**Comment by aclifton314** [comment]
OK. Here is the result of the installation:
```python
(dask-cudf) [aclifton@hn ~]$ conda install -c rapidsai -c conda-forge dask-cudf
Collecting package metadata (current_repodata.json): done
Solving environment: |
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::cudnn==8.1.0.77=h90431f1_0
  - conda-forge/linux-64::cutensor==1.2.2.5=h96e36e3_3
  - conda-forge/linux-64::nccl==2.9.8.1=hdc17891_0
  - conda-forge/linux-64::cupy==8.6.0=py37h3c5eebb_0
  - rapidsai/linux-64::cudf==0.19.2=cuda_11.2_py37_gab3b3f653a_0
done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.4
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/aclifton/anaconda3/envs/dask-cudf

  added / updated specs:
    - dask-cudf


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dask-cudf-0.19.2           |py37_gab3b3f653a_0          97 KB  rapidsai
    ------------------------------------------------------------
                                           Total:          97 KB

The following NEW packages will be INSTALLED:

  dask-cudf          rapidsai/linux-64::dask-cudf-0.19.2-py37_gab3b3f653a_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
dask-cudf-0.19.2     | 97 KB     | ##################################################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
And here is the new error:
```python
Traceback (most recent call last):
  File "lcs_dask.py", line 4, in <module>
    import dask_cudf
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/dask_cudf/__init__.py", line 3, in <module>
    import cudf
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/__init__.py", line 4, in <module>
    validate_setup()
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/utils/gpu_utils.py", line 63, in validate_setup
    raise e
  File "/home/aclifton/anaconda3/envs/dask-cudf/lib/python3.7/site-packages/cudf/utils/gpu_utils.py", line 60, in validate_setup
    gpus_count = getDeviceCount()
  File "rmm/_cuda/gpu.pyx", line 134, in rmm._cuda.gpu.getDeviceCount
rmm._cuda.gpu.CUDARuntimeError: cudaErrorInitializationError: initialization error
```

**Comment by jakirkham** [comment]
Thanks!

What happens when running `nvidia-smi`?

**Comment by aclifton314** [comment]
@jakirkham much thanks for your help and persistence!
```
(dask-cudf) [aclifton@g003 bert_classifier]$ nvidia-smi
Thu May 13 16:17:32 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64.00    Driver Version: 440.64.00    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:18:00.0 Off |                  Off |
| N/A   44C    P0    72W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  On   | 00000000:3B:00.0 Off |                  Off |
| N/A   38C    P0    70W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla V100-SXM2...  On   | 00000000:86:00.0 Off |                  Off |
| N/A   39C    P0    68W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  On   | 00000000:AF:00.0 Off |                  Off |
| N/A   43C    P0    70W / 300W |      0MiB / 32510MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by jakirkham** [comment]
Ofc :)

Could you please install `cudatoolkit=10.2`? It looks like `11.2` was installed (see `conda list` above), but the system only supports `10.2` (see `conda info` above)

**Comment by aclifton314** [comment]
Is `conda install -c nvidia cudatoolkit=10.2` sufficient?

**Comment by jakirkham** [comment]
Would make sure `conda-forge` and `rapidsai` are included as well

**Comment by jakirkham** [comment]
To simplify things going forward, it might be worth just adding these channels to this environment. Here's a relevant SO answer ( https://stackoverflow.com/a/51747791 ) on that. This way one can just do `conda install`

**Comment by aclifton314** [comment]
Awesome! That solved everything! I'm now able to import it successfully, although I'm getting another error when my script continues to run. I will open up a separate issue for that.

**Comment by jakirkham** [comment]
Woot! 🥳 Glad to hear it Alex 😄

Sounds good. Will keep a lookout for the new issue
