### ISSUE TITLE
Failure if UCP is not installed

### ISSUE THREAD

**Issue by quasiben** [rapidsai/dask-cuda#691]
I tried running latest in branch-21.08 and got an error when starting dask-cuda-worker.   This is probably switching the ucp check in https://github.com/rapidsai/dask-cuda/blob/a0217f45e78d8f786dd0f631e38c0d9b310fb6d2/dask_cuda/utils.py#L195 to one of the flags listed in top the of utils file:

```
(rapids-21.08) bzaitlen@dgx13:/tmp/bzaitlen$ dask-cuda-worker 127.0.0.1:8786
Traceback (most recent call last):
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/bin/dask-cuda-worker", line 8, in <module>
    sys.exit(go())
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/cli/dask_cuda_worker.py", line 363, in go
    main()
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/cli/dask_cuda_worker.py", line 310, in main
    worker = CUDAWorker(
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/cuda_worker.py", line 216, in __init__
    self.nannies = [
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/cuda_worker.py", line 227, in <listcomp>
    interface=_get_interface(interface, host, i, net_devices),
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/cuda_worker.py", line 43, in _get_interface
    return interface or get_ucx_net_devices(
  File "/datasets/bzaitlen/miniconda3/envs/rapids-21.08/lib/python3.8/site-packages/dask_cuda/utils.py", line 195, in get_ucx_net_devices
    if ucp.get_ucx_version() >= (1, 11, 0) and ucx_net_devices == "auto":
NameError: name 'ucp' is not defined
(rapids-21.08) bzaitlen@dgx13:/tmp/bzaitlen$ conda list ucp
# packages in environment at /datasets/bzaitlen/miniconda3/envs/rapids-21.08:
#
# Name
```

**Comment by pentschev** [comment]
Note that the failure isn't checking the version, but rather that `ucp` isn't defined, meaning importing it failed. I've had some similar issues earlier today where it seems like my environment was getting upgraded to `cudatoolkit=11.4` and the machine only supports 11.2. Could you check whether you have the correct `cudatoolkit` installed and if `import ucp` fails too?

Also, `conda list ucp` won't return anything as the package name is `ucx-py`.

**Comment by quasiben** [comment]
> Also, conda list ucp won't return anything as the package name is ucx-py

D'oh I forgot this

**Comment by quasiben** [comment]
I have the correct `cudatoolkit` and `ucx` is not installed:

```
(rapids-21.08) bzaitlen@dgx13:/tmp/bzaitlen$ conda list ucx
# packages in environment at /datasets/bzaitlen/miniconda3/envs/rapids-21.08:
#
# Name                    Version                   Build  Channel
(rapids-21.08) bzaitlen@dgx13:/tmp/bzaitlen$ conda list cudatoolkit
# packages in environment at /datasets/bzaitlen/miniconda3/envs/rapids-21.08:
#
# Name                    Version                   Build  Channel
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
```

**Comment by pentschev** [comment]
Ah ok, so this is only an issue when `ucx-py` is not installed. I'll send a PR to fix it in a few moments.
