### ISSUE TITLE
[BUG] Dask-CUDA scheduler fails to start w/ UCXError: Device is busy

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#726]
What's the best way to cleanly, synchronously shutdown a dask-cuda cluster?

I usually `pkill dask`, which takes down scheduler and workers, though it seems I must wait "a minute" to start a new scheduler and workers.

Even when I can see no remaining dask processes with `ps aux | grep dask`, when I start a scheduler with UCX protocol and nvlink, but no infiniband, the scheduler fails to start with:
```
distributed.scheduler - INFO - -----------------------------------------------
distributed.http.proxy - INFO - To route to workers diagnostics web server ple
ase install jupyter-server-proxy: python -m pip install jupyter-server-proxy  distributed.scheduler - INFO - -----------------------------------------------
distributed.scheduler - INFO - Clear task state                               [1631820637.188662] [rl-dgx2-r13-u7-rapids-dgx201:1716096:0]            sock.c
:407  UCX  ERROR bind(fd=69 addr=0.0.0.0:8786) failed: Address already in use Traceback (most recent call last):
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/cli/dask_scheduler.py", line 208, in main                                      loop.run_sync(run)           
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/tornado/i
oloop.py", line 530, in run_sync                                                  return future_cell[0].result()
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/cli/dask_scheduler.py", line 204, in run
    await scheduler 
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/core.py", line 283, in _
    await self.start()            
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distributed/scheduler.py", line 3912, in start
    await self.listen(                                                          File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/core.py", line 401, in listen                                                  listener = await listen(                                                  
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/comm/core.py", line 206, in _                                                  await self.start()      
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distribut
ed/comm/ucx.py", line 404, in start                                               self.ucp_server = ucx_create_listener(serve_forever, port=self._input_port
)                                      
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/ucp/core.py", line 969, in create_listener
    return _get_ctx().create_listener(                                        
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/ucp/core.py", line 268, in create_listener
    ucx_api.UCXListener(            
  File "ucp/_libs/ucx_listener.pyx", line 101, in ucp._libs.ucx_api.UCXListener.__init__                                                                    
  File "ucp/_libs/utils.pyx", line 108, in ucp._libs.ucx_api.assert_ucs_status
ucp.exceptions.UCXError: Device is busy 

During handling of the above exception, another exception occurred:           
                                       
Traceback (most recent call last):
  File "/home/rgelhausen/conda/envs/test/bin/dask-scheduler", line 33, in <module>                                   
    sys.exit(load_entry_point('distributed==2021.9.0', 'console_scripts', 'dask-scheduler')())                                                              
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 217, in go                                    
    main()                                                                    
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)                                         
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/click/core.py", line 782, in main                                                      
    rv = self.invoke(ctx)              
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/click/core.py", line 1066, in invoke      
    return ctx.invoke(self.callback, **ctx.params)                            
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/click/core.py", line 610, in invoke       
    return callback(*args, **kwargs)
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 212, in main                                  
    logger.info("End scheduler at %r", scheduler.address)                     
  File "/home/rgelhausen/conda/envs/test/lib/python3.8/site-packages/distributed/core.py", line 357, in address      
    raise ValueError("cannot get address of non-running Server")   
ValueError: cannot get address of non-running Server   
```

**Comment by pentschev** [comment]
This is because of the way UCX handles the `TIME_WAIT` state, and should only happen when using TCP without IB, it is what you're running, right?

You should be able to prevent that by setting `UCX_TCP_CM_REUSEADDR=y`. Could you try and see if you can circumvent the wait?

**Comment by randerzander** [comment]
> You should be able to prevent that by setting UCX_TCP_CM_REUSEADDR=y. Could you try and see if you can circumvent the wait?

Yes, now I can restart my scheduler immediately. This is greatly speeding up test cycles. Thanks!
