### ISSUE TITLE
CI fails: "ValueError: unsupported pickle protocol: 5"

### ISSUE THREAD

**Issue by madsbk** [rapidsai/dask-cuda#746]
The CI fails with a `ValueError: unsupported pickle protocol: 5` error currently. 
This should be fixed in https://github.com/dask/distributed/pull/5380

```
distributed.core - ERROR - unsupported pickle protocol: 5
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/core.py", line 546, in handle_stream
    msgs = await comm.read()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/ucx.py", line 339, in read
    allow_offload=self.allow_offload,
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/comm/utils.py", line 62, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/core.py", line 112, in loads
    frames[0], object_hook=_decode_default, use_list=False, **msgpack_opts
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/core.py", line 104, in _decode_default
    sub_header, sub_frames, deserializers=deserializers
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 476, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 408, in deserialize
    return loads(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/distributed/protocol/cuda.py", line 28, in cuda_loads
    return loads(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/comm/serialize.py", line 22, in cuda_deserialize_cudf_object
    return Serializable.device_deserialize(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/abc.py", line 142, in device_deserialize
    obj = typ.deserialize(header, frames)
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/dataframe.py", line 546, in deserialize
    header, frames[header["index_frame_count"] :]
  File "/opt/conda/envs/rapids/lib/python3.7/site-packages/cudf/core/frame.py", line 82, in deserialize
    cls_deserialize = pickle.loads(header["type-serialized"])
ValueError: unsupported pickle protocol: 5
```

**Comment by pentschev** [comment]
Awesome, thanks a lot for tracking and fixing the issue @madsbk !

**Comment by madsbk** [comment]
Fixed now that https://github.com/dask/distributed/pull/5380 has been merged
