### ISSUE TITLE
How to read massive data files (60G) on multiple GPUs? client.persist takes forever

### ISSUE THREAD

**Issue by 666-sudo** [rapidsai/dask-cuda#769]
I want to read dataframes on multiple GPUs before running XGBoost. However, `client.persist `takes forever for me...

My current implementation follows:
```
cluster = LocalCUDACluster(n_workers=3) ## I have three GPUs 
client = Client(cluster)
df_train_feature = pd.DataFrame(train_feature, ... )
df_train_label = pd.DataFrame(y_train[:,2756], ...)
df_train_feature = dask_cudf.from_cudf(df_train_feature, npartitions=38663)
df_train_label = dask_cudf.from_cudf(df_train_label, npartitions=38663)
```

*******************
`X_train, y_train = client.persist([df_train_feature, df_train_label])`
*******************
 I am currently on this step and it takes forever for `client.persist` while the memory usage of GPUs from nvidia-smi doesn't change. 

```
tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <zmq.eventloop.ioloop.ZMQIOLoop object at 0x7f3460386dd0>>, <Task finished coro=<Cluster._sync_cluster_info() done, defined at ****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/cluster.py:98> exception=OSError('Timed out trying to connect to tcp://127.0.0.1:42397 after 30 s')>)
Traceback (most recent call last):
  File "****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/comm/core.py", line 285, in connect
    timeout=min(intermediate_cap, time_left()),
  File "****software/anaconda3/envs/xgbgpu/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ****anaconda3/envs/xgbgpu/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/tornado/ioloop.py", line 765, in _discard_future_result
    future.result()
  File "****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 101, in _sync_cluster_info
    value=copy.copy(self._cluster_info),
  File "****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py", line 796, in send_recv_from_rpc
    comm = await self.live_comm()
  File ****software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/core.py", line 757, in live_comm
    **self.connection_args,
  File "****/software/anaconda3/envs/xgbgpu/lib/python3.7/site-packages/distributed/comm/core.py", line 309, in connect
    ) from active_exception
OSError: Timed out trying to connect to tcp://127.0.0.1:42397 after 30 s
IOStream.flush timed out
```

`wait([X_train, y_train])`

My next steps are planned as:

Xy = dxgb.DaskDeviceQuantileDMatrix(client, X_train, y_train)

booster = dxgb.train(
                 client,
                 {
                     "objective": "binary:logistic",
                     "tree_method": "gpu_hist",
                 },
                 Xy, 
                 num_boost_round=1000,
                 early_stopping_rounds=10
              )["booster"]

What would be an efficient way to read the massive data on multiple GPUs before the XGBoost computation? 
Thank you for your help in advance.

**Comment by quasiben** [comment]
When you call `dask_cudf.from_cudf(...)` this pulls all the data from host memory to the device.  It is much better if you can read the data with dask-cuDF.  Is this possible ?

**Comment by pentschev** [comment]
No answer from user, closing.
