### ISSUE TITLE
[Error] LocalCUDACluster throws ImportError: libnuma.so.1

### ISSUE THREAD

**Issue by mlahir1** [rapidsai/dask-cuda#822]
Repro code: with latest 22.02 build also happens with 21.12
```
>>> from dask_cuda import LocalCUDACluster
>>> LocalCUDACluster()

distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/distributed/comm/ucx.py", line 549, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/conda/envs/rapids-22.02/lib/python3.8/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
LocalCUDACluster(498cec14, 'tcp://127.0.0.1:36357', workers=8, threads=8, memory=754.41 GiB)
```

**Comment by beckernick** [comment]
Can you provide additional system and environment information and setup? I'm unable to reproduce this on a DGX-1 using CUDA 11.2, driver 460.32.03 with an environment built via `conda create -n rapids-22.02 -c rapidsai-nightly -c nvidia -c conda-forge rapids=22.02 python=3.8 cudatoolkit=11.0 dask-sql`

**Comment by mlahir1** [comment]
here is the driver version:
```
NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4 
Ubuntu 18.04.5 LTS on docker container
```

Hardware is V100's

**Comment by mlahir1** [comment]
installing libnuma fixed it. thanks, 
```
apt-get install libnuma-dev
```
