### ISSUE TITLE
Trying to start a cluster in SageMaker Studio Lab

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#865]
In Amazon's SageMaker Studio Lab, you can get access to an instance w/ a single GPU.

SageMaker Studio Lab lets you create and use your own conda environments with its notebook instance, and you can use cudf and dask_cudf directly.

I wanted to start the Dask Dashboard so I could monitor DAG execution, but creating a LocalCUDACluster failed:
```
from dask_cuda import LocalCUDACluster

cluster = LocalCUDACluster()
```

Result:
```
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/distributed/comm/ucx.py", line 548, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
```

Perhaps there's some arguments I can supply that prevents this attempted invalid import?

**Comment by randerzander** [comment]
I am able to create a Dask CPU LocalCluster:
```
from dask.distributed import Client, LocalCluster

cluster = LocalCluster()
client = Client(cluster)
client
```
```
<h3 style="margin-bottom: 0px;">Client</h3>
        <p style="color: #9D9D9D; margin-bottom: 0px;">Client-21578f52-94e1-11ec-82d0-42041b1ec31e</p>
        

Connection method: Cluster object | Cluster type: distributed.LocalCluster
-- | --
Dashboard:  http://127.0.0.1:46847/status |  



        <details>
            <summary style="margin-bottom: 20px;">
                <h3 style="display: inline;">Scheduler Info</h3>
            </summary></details></div></div></details>
```

**Comment by pentschev** [comment]
UCX-Py requires libnuma, can this be installed from the system? Otherwise, `LocalCUDACluster(protocol="tcp")` may work.

**Comment by randerzander** [comment]
I purposely did not install UCX, given I knew this environment would use a T4.

Creating w/ `protocol="tcp"` has the same issue:
```
distributed.preloading - INFO - Import preload module: dask_cuda.initialize
Unable to start CUDA Context
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/dask_cuda/initialize.py", line 32, in _create_cuda_context
    distributed.comm.ucx.init_once()
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/distributed/comm/ucx.py", line 68, in init_once
    ucx_config = _scrub_ucx_config()
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/distributed/comm/ucx.py", line 548, in _scrub_ucx_config
    from ucp import get_config, get_ucx_version
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/__init__.py", line 21, in <module>
    from .core import *  # noqa
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/core.py", line 16, in <module>
    from . import comm
  File "/home/studio-lab-user/.conda/envs/rapids-22.04-nightly/lib/python3.9/site-packages/ucp/comm.py", line 8, in <module>
    from ._libs import arr, ucx_api
ImportError: libnuma.so.1: cannot open shared object file: No such file or directory
```

**Comment by pentschev** [comment]
Hmm, but with UCX-Py being installed Dask will attempt to import it, because this is not currently a use case that was predicted (UCX-Py installed but no UCX). Dask also needs to import UCX-Py when creating the cluster to initialize it before spinning worker threads.

Can UCX-Py be uninstalled?

**Comment by randerzander** [comment]
Ok, this is resolved by making sure I don't have UCX or ucx-py in my environment.
