### ISSUE TITLE
handle_compute received unexpected keyword argument run_spec

### ISSUE THREAD

**Issue by caleb-recursion** [rapidsai/dask-cuda#936]
Hi there,

I am starting a dask cluster using dask-kubernetes, and submitting work to it using the latest prefect 2.0 beta. CPU bound jobs work fine. To test GPU workload, I followed [this doc](https://kubernetes.dask.org/en/latest/kubecluster.html#gpus), used your base image of `rapidsai/rapidsai:22.06-cuda11.4-base-ubuntu20.04-py3.8` and ran the command dask-cuda-worker in the pod template. The pod starts, and the worker is able to register to the scheduler, but the dask-cuda-worker dies after getting work. The following error is thrown.

```
2022-06-20 14:36:59,451 - distributed.worker - INFO -         Registered to: tcp://dask-root-89c2e488-b.default:8786
2022-06-20 14:36:59,451 - distributed.worker - INFO - -------------------------------------------------
2022-06-20 14:36:59,452 - distributed.core - INFO - Starting established connection
2022-06-20 14:36:59,455 - distributed.core - ERROR - handle_compute_task() got an unexpected keyword argument 'run_spec'
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 658, in handle_stream
    handler(**merge(extra, msg))
TypeError: handle_compute_task() got an unexpected keyword argument 'run_spec'
2022-06-20 14:36:59,456 - tornado.application - ERROR - Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOLoop object at 0x7f812c0ced90>>, <Task finished name='Task-9' coro=<Worker.handle_scheduler() done, defined at /opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py:177> exception=CommClosedError('Comm <TCP (closed) Worker->Scheduler local=tcp://10.0.3.18:45342 remote=tcp://dask-root-89c2e488-b.default:8786> already closed.')>)
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 180, in wrapper
    return await method(self, *args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/worker.py", line 1249, in handle_scheduler
    await self.handle_stream(comm)
  File "/opt/conda/envs/rapids/lib/python3.8/site-packages/distributed/core.py", line 658, in handle_stream
    handler(**merge(extra, msg))
TypeError: handle_compute_task() got an unexpected keyword argument 'run_spec'
```

I have tested the latest version of everything, and also versions of rapids, dask, and dask-kubernetes from early february, in case it was a recent change. Both yield the same error.

Any guidance on how to debug would really help. Thanks alot!

**Comment by pentschev** [comment]
Hi @caleb-recursion , could you also post the a minimal reproducer of the client code you submit when the error occurs?

**Comment by caleb-recursion** [comment]
And I followed this guide to deploy the prefect agent and job to an existing k8s cluster: https://orion-docs.prefect.io/tutorials/kubernetes-flow-runner/

**Comment by caleb-recursion** [comment]
FLOW_BUCKET is any S3 bucket.

**Comment by pentschev** [comment]
Nice to see this got resolved, thanks for updating here @caleb-recursion !
