### ISSUE TITLE
AttributeError: 'LocalCUDACluster' object has no attribute 'status' when using Visual Profiler

### ISSUE THREAD

**Issue by garanews** [rapidsai/dask-cuda#94]
I would use nvidia visual profiler (from remote) to analyze my code running on a server with multiple gpu.
On a server I started "nvidia-cuda-mps-control -d". (tried both with same user run the script inside virtualenv and with sudo, same result)
On my workstation (following a guide ) I am able to connect and set everythink ready for the analysis (setting profiling all processes).
Returning on the server and laucning manually my app I receive this error:

```
(tf_gpu) dask@server:~$ python zarr0.py
Traceback (most recent call last):
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 227, in initialize
    self.cuInit(0)
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuInit results in CUDA_ERROR_UNKNOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "zarr0.py", line 135, in <module>
    cluster = LocalCUDACluster(n_workers=8, threads_per_worker=8)
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/dask_cuda/local_cuda_cluster.py", line 75, in __init__
    self.device_memory_limit = get_device_total_memory(0)
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/dask_cuda/utils.py", line 22, in get_device_total_memory
    with cuda.gpus[index]:
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
    return self.lst[devnum]
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 336, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 270, in __getattr__
    self.initialize()
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 230, in initialize
    raise CudaSupportError("Error at driver init: \n%s:" % e)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init:
[999] Call to cuInit results in CUDA_ERROR_UNKNOWN:
Exception ignored in: <object repr() failed>
Traceback (most recent call last):
  File "/home/dask/miniconda3/envs/tf_gpu/lib/python3.6/site-packages/distributed/deploy/spec.py", line 260, in __del__
AttributeError: 'LocalCUDACluster' object has no attribute 'status'
```

Thsi error appears if  /usr/bin/nvidia-cuda-mps-control is active, but to profile multi-process apps this must be started, right?

Any suggestion?

**Comment by pentschev** [comment]
To be honest, I haven't spent a lot of time trying to profile code with dask-cuda, but on a single machine it should work with `nvprof --profile-child-processes`, did you try that?

I think though there may still be some issue with that, as per my comment https://github.com/rapidsai/dask-cuda/issues/74#issuecomment-504418319, but I haven't yet had the chance to confirm.

**Comment by pentschev** [comment]
This seems to have gone stale, so I'm closing for now. Feel free to reopen if there are any further developments.
