### ISSUE TITLE
pynvml.nvml.NVMLError_LibRmVersionMismatch: RM has detected an NVML/RM version mismatch.

### ISSUE THREAD

**Issue by benjha** [rapidsai/dask-cuda#949]
Hi dask-cuda team,

I've compiled from source cudf and dask-cuda v22.06 for ppc64le (Summit). At this point, I am trying to run a dask-cuda cluster using TCP and  getting this error:

```
Traceback (most recent call last):
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/bin/dask-scheduler", line 33, in <module>
    sys.exit(load_entry_point('distributed==2022.5.2', 'console_scripts', 'dask-scheduler')())
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 230, in main
    asyncio.run(run())
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/cli/dask_scheduler.py", line 192, in run
    scheduler = Scheduler(
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/scheduler.py", line 2950, in __init__
    import distributed.dashboard.scheduler
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/dashboard/scheduler.py", line 6, in <module>
    from distributed.dashboard.components.nvml import gpu_doc  # noqa: 1708
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/dashboard/components/nvml.py", line 23, in <module>
    NVML_ENABLED = nvml.device_get_count() > 0
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/diagnostics/nvml.py", line 69, in device_get_count
    init_once()
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/distributed/diagnostics/nvml.py", line 44, in init_once
    pynvml.nvmlInit()
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py", line 1450, in nvmlInit
    nvmlInitWithFlags(0)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py", line 1440, in nvmlInitWithFlags
    _nvmlCheckReturn(ret)
  File "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py", line 765, in _nvmlCheckReturn
    raise NVMLError(ret)
pynvml.nvml.NVMLError_LibRmVersionMismatch: RM has detected an NVML/RM version mismatch.

```
I installed pynvml=11.4.1, dask=2022.05.2 distributed=2022.05.2, cuda 11.5.2 and V100's driver 450.80.02 

I am not aware if RM is a dependency installed during the compilation process or is related to system's configuration. What does RM stand for ? 

@pentschev 

Thanks

**Comment by benjha** [comment]
Hi @pentschev,

This is the output:

```
$  strace python -c "from distributed.diagnostics.nvml import init_once; init_once()" 2>&1 | grep nvidia-ml
openat(AT_FDCWD, "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/lib-dynload/../../power9/libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/lib-dynload/../../libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/autofs/nccs-svm1_sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/bin/../lib/power9/libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/autofs/nccs-svm1_sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/bin/../lib/libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sw/summit/spack-envs/base/opt/linux-rhel8-ppc64le/gcc-9.3.0/spectrum-mpi-10.4.0.3-20210112-6depextb6p6ulrvmehgtbskbmcsyhtdi/lib/libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/sw/summit/cuda/11.5.2/lib64/libnvidia-ml.so.1", O_RDONLY|O_CLOEXEC) = 3
```

This is the full list of libnvidia-ml files in `/sw/summit/cuda/11.5.2/lib64/` 

```
$ ls -h /sw/summit/cuda/11.5.2/lib64/*ml*
/sw/summit/cuda/11.5.2/lib64/libnvidia-ml.so  
/sw/summit/cuda/11.5.2/lib64/libnvidia-ml.so.1  
/sw/summit/cuda/11.5.2/lib64/libnvidia-ml.so.495.29.05
```

In addition, there is symbolic link to `libnvidia-ml.so.450.80.02` in `/usr/lib64`.

**Comment by benjha** [comment]
Thanks @pentschev for the hint, that works.

Now I need to figure out how to control things at runtime. For example, when testing cugraph without `LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH`, appears a similar error as above:

```
$ pytest test_louvain.py
ImportError while loading conftest '/autofs/nccs-svm1_sw/summit/ums/gen119/nvrapids/src/nvrapids_v22.06.00_src/cugraph_v22.06.00/python/cugraph/cugraph/tests/conftest.py'.
conftest.py:23: in <module>
    from cugraph.dask.comms import comms as Comms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/__init__.py:14: in <module>
    from cugraph.community import (
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/community/__init__.py:14: in <module>
    from cugraph.community.louvain import louvain
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/community/louvain.py:14: in <module>
    from cugraph.community import louvain_wrapper
cugraph/community/louvain_wrapper.pyx:21: in init cugraph.community.louvain_wrapper
    ???
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/__init__.py:14: in <module>
    from cugraph.structure.graph_classes import (Graph,
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_classes.py:15: in <module>
    from .graph_implementation import (simpleGraphImpl,
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_implementation/__init__.py:14: in <module>
    from .simpleGraph import simpleGraphImpl
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_implementation/simpleGraph.py:14: in <module>
    from cugraph.structure import graph_primtypes_wrapper
cugraph/structure/graph_primtypes_wrapper.pyx:27: in init cugraph.structure.graph_primtypes_wrapper
    ???
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/dask/__init__.py:14: in <module>
    from .link_analysis.pagerank import pagerank
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/dask/link_analysis/pagerank.py:17: in <module>
    from cugraph.dask.common.input_utils import (get_distributed_data,
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/dask/common/input_utils.py:22: in <module>
    import cugraph.dask.comms.comms as Comms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/dask/comms/comms.py:18: in <module>
    from raft.dask.common.comms import Comms as raftComms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/raft-22.6.0-py3.8-linux-ppc64le.egg/raft/dask/__init__.py:16: in <module>
    from .common.comms import Comms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/raft-22.6.0-py3.8-linux-ppc64le.egg/raft/dask/common/__init__.py:16: in <module>
    from .comms import Comms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/raft-22.6.0-py3.8-linux-ppc64le.egg/raft/dask/common/comms.py:17: in <module>
    from .ucx import UCX
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/raft-22.6.0-py3.8-linux-ppc64le.egg/raft/dask/common/ucx.py:16: in <module>
    import ucp
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/ucp/__init__.py:47: in <module>
    pynvml.nvmlInit()
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py:1450: in nvmlInit
    nvmlInitWithFlags(0)
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py:1440: in nvmlInitWithFlags
    _nvmlCheckReturn(ret)
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/pynvml/nvml.py:765: in _nvmlCheckReturn
    raise NVMLError(ret)
E   pynvml.nvml.NVMLError_LibRmVersionMismatch: RM has detected an NVML/RM version mismatch.
```
and now with `LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH`:

```
 LD_LIBRARY_PATH=/usr/lib64:$LD_LIBRARY_PATH pytest test_louvain.py
ImportError while loading conftest '/autofs/nccs-svm1_sw/summit/ums/gen119/nvrapids/src/nvrapids_v22.06.00_src/cugraph_v22.06.00/python/cugraph/cugraph/tests/conftest.py'.
conftest.py:23: in <module>
    from cugraph.dask.comms import comms as Comms
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/__init__.py:14: in <module>
    from cugraph.community import (
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/community/__init__.py:14: in <module>
    from cugraph.community.louvain import louvain
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/community/louvain.py:14: in <module>
    from cugraph.community import louvain_wrapper
cugraph/community/louvain_wrapper.pyx:21: in init cugraph.community.louvain_wrapper
    ???
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/__init__.py:14: in <module>
    from cugraph.structure.graph_classes import (Graph,
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_classes.py:15: in <module>
    from .graph_implementation import (simpleGraphImpl,
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_implementation/__init__.py:14: in <module>
    from .simpleGraph import simpleGraphImpl
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cugraph-22.6.0+0.gfb99d2d7.dirty-py3.8-linux-ppc64le.egg/cugraph/structure/graph_implementation/simpleGraph.py:14: in <module>
    from cugraph.structure import graph_primtypes_wrapper
cugraph/structure/graph_primtypes_wrapper.pyx:1: in init cugraph.structure.graph_primtypes_wrapper
    ???
cugraph/structure/graph_primtypes.pyx:24: in init cugraph.structure.graph_primtypes
    ???
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cudf/__init__.py:5: in <module>
    validate_setup()
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/cudf/utils/gpu_utils.py:95: in validate_setup
    cuda_runtime_version = runtimeGetVersion()
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/rmm/_cuda/gpu.py:87: in runtimeGetVersion
    major, minor = numba.cuda.runtime.get_version()
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py:111: in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py:81: in safe_cuda_api_call
    self._check_error(fname, retcode)
/sw/summit/ums/gen119/nvrapids/bin/anaconda-2022.05/envs/nvrapids-v22.06.00/lib/python3.8/site-packages/numba/cuda/cudadrv/runtime.py:89: in _check_error
    raise CudaRuntimeAPIError(retcode, msg)
E   numba.cuda.cudadrv.runtime.CudaRuntimeAPIError: [304] Call to cudaRuntimeGetVersion results in CUDA_ERROR_OPERATING_SYSTEM
```

**Comment by pentschev** [comment]
The way conda works is that it doesn't ship driver files, only CUDA runtime ones. IOW, you should have the CUDA runtime files under `/sw/summit/cuda/11.5.2`, but only rely on the driver runtime files from `/usr/lib64`. I'm not sure how `/sw/summit/cuda/11.5.2` was populated, but it seems like you have also driver files in there, which you don't get if you install CUDA under `/usr/local/cuda-VERSION` from the CUDA toolkit download page with the `runtime` package, at least if you select not to install the driver from that package as well, which may be what happened in that case.

The latest issue you had there is probably because you now get the right driver files but older CUDA runtime files, I think if you can get a CUDA install that doesn't contain driver files, that may resolve the issue.

I'm closing this for now then, but please feel free to reopen if needed.
