### ISSUE TITLE
add_worker() got an unexpected keyword argument 'server_id'

### ISSUE THREAD

**Issue by randerzander** [rapidsai/dask-cuda#973]
On the latest rapidsai-dev-nightly image:
`FROM rapidsai/rapidsai-dev-nightly:22.10-cuda11.5-devel-ubuntu20.04-py3.9`

I'm able to start a LocalCUDACluster fine.

When I try to start dask-scheduler and dask-cuda-worker from the CLI, I get repeating errors:

scheduler trace:
```
(rapids) root@ipp1-3303:/pynds# dask-scheduler  
2022-08-09 19:30:21,016 - distributed.scheduler - INFO - -------------------------------------
----------
2022-08-09 19:30:21,802 - distributed.scheduler - INFO - State start
2022-08-09 19:30:21,815 - distributed.scheduler - INFO - -------------------------------------
----------
2022-08-09 19:30:21,815 - distributed.scheduler - INFO - Clear task state
2022-08-09 19:30:21,816 - distributed.scheduler - INFO -   Scheduler at:     tcp://172.17.0.2:
8786
2022-08-09 19:30:21,816 - distributed.scheduler - INFO -   dashboard at:                     :
8787
add_worker() got an unexpected keyword argument 'server_id'
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/utils.py", line 761, in
 wrapper
    return await func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'server_id'
2022-08-09 19:30:39,607 - distributed.core - ERROR - Exception while handling op register-work
er
Traceback (most recent call last):
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/core.py", line 588, in 
handle_comm
    result = await result
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/distributed/utils.py", line 761, in
 wrapper
    return await func(*args, **kwargs)
TypeError: add_worker() got an unexpected keyword argument 'server_id'
add_worker() got an unexpected keyword argument 'server_id'
```
worker trace:
```
2022-08-09 19:30:39,635 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-5e3a7
490-fb0b-4d17-afc4-8d586375b39e
2022-08-09 19:30:39,635 - distributed.worker - INFO - Starting Worker plugin RMMSetup-dda7de20
-d684-4fdb-a342-3f1a4902cc30
2022-08-09 19:30:39,635 - distributed.worker - INFO - Starting Worker plugin PreImport-9eac30c
4-f35d-4c31-b93f-90c741a23155
2022-08-09 19:30:39,635 - distributed.worker - INFO - Starting Worker plugin RMMSetup-d4e42c1d
-078e-4185-91dc-5d6bdf3a18c1
2022-08-09 19:30:39,635 - distributed.worker - INFO - ----------------------------------------
---------
2022-08-09 19:30:39,636 - distributed.worker - INFO - Starting Worker plugin PreImport-4c0b688
9-476d-4e9b-9722-c5b31f6eb4a7
2022-08-09 19:30:39,636 - distributed.worker - INFO - Starting Worker plugin CPUAffinity-215ba
7d2-a763-4f1e-9d9e-a64a295ab978
2022-08-09 19:30:39,636 - distributed.worker - INFO - ----------------------------------------
---------
^C2022-08-09 19:32:12,623 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:366
65
2022-08-09 19:32:12,623 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:42387
2022-08-09 19:32:12,623 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:43475
2022-08-09 19:32:12,623 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:40219
2022-08-09 19:32:12,624 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:40119
2022-08-09 19:32:12,624 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:34443
2022-08-09 19:32:12,624 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:42471
2022-08-09 19:32:12,624 - distributed.worker - INFO - Stopping worker at tcp://127.0.0.1:44625
2022-08-09 19:32:12,623 - distributed.worker - INFO - Closed worker has not yet started: Statu
s.init
2022-08-09 19:32:12,624 - distributed.worker - INFO - Closed worker has not yet started: Statu
s.init
2022-08-09 19:32:12,624 - distributed.nanny - INFO - Closing Nanny at 'tcp://127.0.0.1:46281'.
2022-08-09 19:32:12,625 - distributed.nanny - INFO - Nanny asking worker to close
```
*Edit*: A different worker trace:
```
(rapids) root@ipp1-3303:/rapids/notebooks# dask-cuda-worker localhost:8786
Traceback (most recent call last):                                                            
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 57
9, in _build_master                                                                               ws.require(__requires__)                                                                  
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 897, in require                                                                                 
    needed = self.resolve(parse_requirements(requirements))                 
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 788, in resolve                                                                                 
    raise VersionConflict(dist, req).with_context(dependent_req)    
pkg_resources.ContextualVersionConflict: (distributed 2022.5.1+13.gf76c40bb (/opt/conda/envs/rapids/lib/python3.9/site-packages), Requirement.parse('distributed==2022.7.1'), {'dask-cuda'})
                                                                                              
During handling of the above exception, another exception occurred:                                                                                                                         
Traceback (most recent call last):                                                            
  File "/opt/conda/envs/rapids/bin/dask-cuda-worker", line 33, in <module>                        sys.exit(load_entry_point('dask-cuda==22.10.0a0+g7abc6a1', 'console_scripts', 'dask-cuda-w
orker')())                                                                                    
  File "/opt/conda/envs/rapids/bin/dask-cuda-worker", line 25, in importlib_load_entry_point      return next(matches).load()                                                               
  File "/opt/conda/envs/rapids/lib/python3.9/importlib/metadata.py", line 86, in load         
    module = import_module(match.group('module'))                                               File "/opt/conda/envs/rapids/lib/python3.9/importlib/__init__.py", line 127, in import_modul
e                                                                                             
    return _bootstrap._gcd_import(name[level:], package, level)                                 File "<frozen importlib._bootstrap>", line 1030, in _gcd_import             
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked                    File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                             
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load                            File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed                
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import                               File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked                  
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked                             File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module                                         
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.10.0a0+g7abc6a1-py3.9.
egg/dask_cuda/__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.10.0a0+g7abc6a1-py3.9.
egg/dask_cuda/cuda_worker.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/dask_cuda-22.10.0a0+g7abc6a1-py3.9.
egg/dask_cuda/initialize.py", line 5, in <module>
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/numba/__init__.py", line 19, in <mo
dule>
    from numba.core import config
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/numba/core/config.py", line 15, in 
<module>
    import llvmlite.binding as ll
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/llvmlite/binding/__init__.py", line
 4, in <module>
    from .dylib import *
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/llvmlite/binding/dylib.py", line 3,
 in <module>
    from llvmlite.binding import ffi
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/llvmlite/binding/ffi.py", line 175,
 in <module>
    from pkg_resources import resource_filename 
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 32
47, in <module>
    def _initialize_master_working_set():
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 32
21, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 32
59, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 58
1, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 59
4, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/conda/envs/rapids/lib/python3.9/site-packages/pkg_resources/__init__.py", line 78
3, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'distributed==2022.7.1' distribution was not found and
 is required by dask-cuda
```

Package versions:
```
(rapids) root@ipp1-3303:/pynds# conda list | grep dask
dask                      2022.7.1                 pypi_0    pypi
dask-core                 2022.7.1a220722 py_gedfa91e22_16    dask/label/dev
dask-cudf                 22.10.0a0+ge1a4e03          pypi_0    pypi
dask-glm                  0.2.0                      py_1    conda-forge
dask-labextension         5.3.0              pyhd8ed1ab_1    conda-forge
dask-ml                   1.9.0              pyhd8ed1ab_0    conda-forge
dask-sql                  2022.6.0                 pypi_0    pypi
distributed               2022.05.2a220526 py_gf76c40bb_13    dask/label/dev
(rapids) root@ipp1-3303:/pyndds# conda list | grep rapids
# packages in environment at /opt/conda/envs/rapids:
asvdb                     0.4.2               g90e8f2c_40    rapidsai-nightly
cmake_setuptools          0.1.3                      py_0    rapidsai-nightly
datashader                0.13.1a                    py_0    rapidsai-nightly
faiss-proc                1.0.0                      cuda    rapidsai
jupyterlab-nvdashboard    0.8.0a220623              py_11    rapidsai-nightly
libcugraphops             22.10.00a220803 cuda11_g30118552_15    rapidsai-nightly
libcumlprims              22.10.00a220804 cuda11_g2adfe69_0    rapidsai-nightly
libcypher-parser          0.6.2                         1    rapidsai-nightly
librmm                    22.10.00a220807 cuda11_gd3b1dfbe_6    rapidsai-nightly
ptxcompiler               0.2.0            py39h107f55c_0    rapidsai-nightly
ucx-proc                  1.0.0                       gpu    rapidsai-nightly
ucx-py                    0.28.00a220726  py39_g566ed22_0    rapidsai-nightly
```

**Comment by randerzander** [comment]
Looks like this one might be specific to the Docker image and source package builds.

Plain conda installs of nightly packages seem to work

**Comment by pentschev** [comment]
Yes, this looks related to https://github.com/dask/dask/issues/9367#issuecomment-1209418457, could you try pulling all Dask packages from the same channels?

**Comment by randerzander** [comment]
cc @ajschmidt8 re: the dev nightly docker image

**Comment by randerzander** [comment]
I think there are two things happening in this issue. One is `'distributed==2022.7.1' distribution was not found and
 is required by dask-cuda`.

Installing dask, distributed, and dask-cuda from source on respective main branches eliminates that problem.

However, I still have the `TypeError: add_worker() got an unexpected keyword argument 'server_id'` error appearing in the scheduler logs, and my workers are unable to successfully connect.

**Comment by pentschev** [comment]
Instantiating a container from `rapidsai/rapidsai-dev-nightly:22.10-cuda11.5-devel-ubuntu20.04-py3.9` I see what @randerzander mentioned above.

To summarize, there's actually a bunch of problems there. For starters, `dask`, `dask-core` and `distributed` versions don't match. I believe this was a side-effect from that, but `dask-cuda` isn't even listed there, although `dask-cuda-worker` exists:

```
# conda list | egrep "dask|distributed"
dask                      2022.7.1                 pypi_0    pypi
dask-core                 2022.7.1a220722 py_gedfa91e22_16    dask/label/dev
dask-cudf                 22.10.0a0+ge1a4e03          pypi_0    pypi
dask-glm                  0.2.0                      py_1    conda-forge
dask-labextension         5.3.0              pyhd8ed1ab_1    conda-forge
dask-ml                   1.9.0              pyhd8ed1ab_0    conda-forge
dask-sql                  2022.6.0                 pypi_0    pypi
distributed               2022.05.2a220526 py_gf76c40bb_13    dask/label/dev
```

On a fresh instance of that image, I'm able to install all packages correctly with:

```
# pip install git+https://github.com/dask/distributed git+https://github.com/dask/dask git+https://github.com/rapidsai/dask-cuda
```

After that, I can create `dask-scheduler` and `dask-cuda-worker` successfully. Could you try that @randerzander ?

**Comment by wence-** [comment]
You can also get a matching set with `mamba install 'dask>2022.07' 'distributed>2022.07' 'dask-cuda>22.06'`

**Comment by pentschev** [comment]
That doesn't seem to work correctly, Dask is still on 2022.07 despite conda saying it would install 2022.8:

```
# conda list | egrep "dask|distributed"
dask                      2022.7.1                 pypi_0    pypi
dask-core                 2022.8.1a220810 py_ga3c063434_7    dask/label/dev
dask-cuda                 22.10.00a220810 py39_g603db6a_13    rapidsai-nightly
dask-cudf                 22.10.0a0+ge1a4e03          pypi_0    pypi
dask-glm                  0.2.0                      py_1    conda-forge
dask-labextension         5.3.0              pyhd8ed1ab_1    conda-forge
dask-ml                   1.9.0              pyhd8ed1ab_0    conda-forge
dask-sql                  2022.6.0                 pypi_0    pypi
distributed               2022.8.1a220810 py_ge1b9e20f_13    dask/label/dev
```

**Comment by wence-** [comment]
Something is really wrong here; why is the `dask` package installed via pypi/pip (rather than conda)? If I do the `pip uninstall dask` fixed point iteration (I needed to do it twice); and then do `mamba install --force-reinstall 'dask>2022.07' 'distributed>2022.07' 'dask-cuda>22.06'` I have:
```
mamba list | egrep 'dask|distributed'
dask                      2022.8.1a220810 py_ge1b9e20f_13    dask/label/dev
dask-core                 2022.8.1a220810 py_ga3c063434_7    dask/label/dev
dask-cuda                 22.10.00a220810 py39_g603db6a_13    rapidsai-nightly
dask-cudf                 22.10.0a0+ge1a4e03          pypi_0    pypi
dask-glm                  0.2.0                      py_1    conda-forge
dask-labextension         5.3.0              pyhd8ed1ab_1    conda-forge
dask-ml                   1.9.0              pyhd8ed1ab_0    conda-forge
dask-sql                  2022.6.0                 pypi_0    pypi
distributed               2022.8.1a220810 py_ge1b9e20f_13    dask/label/dev```

**Comment by randerzander** [comment]
> After that, I can create dask-scheduler and dask-cuda-worker successfully. Could you try that @randerzander ?

After `python -m pip install .` from the dask-cuda repo directory, conda lists dask_cuda:
```
dask-cuda                 22.10.0a0+13.g603db6a          pypi_0    pypi
```

and I'm able to start the server and workers correctly.

Interestingly, for dask and distributed, `python setup.py install` is sufficient for conda to detect their installation. dask-cuda requires installing explicitly w/ pip to work. I wonder if dask-cuda is missing some build configuration that would let it work similarly?

**Comment by pentschev** [comment]
I'm clueless about `setup.py` and conda interactions, or better yet packaging as a whole. Maybe @jakirkham can shed some light regarding @randerzander 's question above?

**Comment by jrbourbeau** [comment]
Just a heads up that https://github.com/dask/dask/issues/9367 has been resolved (thanks @charlesbluca @jakirkham)

**Comment by wence-** [comment]
@randerzander does this error still persist for you?

**Comment by randerzander** [comment]
No, this was resolved! Thanks!
