### ISSUE TITLE
Launch multiple processes on only one GPU

### ISSUE THREAD

**Issue by zxgx** [rapidsai/dask-cuda#974]
![image](https://user-images.githubusercontent.com/34452939/183809442-cefa8d50-4013-4004-97d3-cd5e92b72b2c.png)

I'm trying to preprocess Criteo 1TB dataset in the way introduced by [NVTabular](https://github.com/NVIDIA-Merlin/NVTabular/blob/main/examples/scaling-criteo/01-Download-Convert.ipynb).
I modified the notebook since my disk doesn't have enough space, and I ran it with the official Merlin-PyTorch docker image.
Here's my script:
```python
import os
import shutil
import glob

import numpy as np
import numba
from dask.distributed import Client
from dask_cuda import LocalCUDACluster

import nvtabular as nvt
from merlin.core.utils import device_mem_size, get_rmm_size


if __name__ == "__main__":
    dask_workdir = "dask_workdir"
    if os.path.exists(dask_workdir):
        shutil.rmtree(dask_workdir)
    os.makedirs(dask_workdir)

    device_limit_frac = 0.8  # Spill GPU-Worker memory to host at this limit.
    device_pool_frac = 0.7

    # Use total device size to calculate device limit and pool_size
    device_size = device_mem_size(kind="total")
    device_limit = int(device_limit_frac * device_size)
    print(f'visible devices: {numba.cuda.gpus}')

    cluster = LocalCUDACluster(
        protocol="tcp",
        n_workers=len(numba.cuda.gpus),
        CUDA_VISIBLE_DEVICES=range(len(numba.cuda.gpus)),
        device_memory_limit=device_limit,
        local_directory=dask_workdir,
        rmm_pool_size=get_rmm_size(device_pool_frac * device_size),
    )

    client = Client(cluster)

    print(client)
    # Specify column names
    cont_names = ["I" + str(x) for x in range(1, 14)]
    cat_names = ["C" + str(x) for x in range(1, 27)]
    cols = ["label"] + cont_names + cat_names

    # Specify column dtypes. Note that "hex" means that
    # the values will be hexadecimal strings that should
    # be converted to int32
    dtypes = {}
    dtypes["label"] = np.int32
    for x in cont_names:
        dtypes[x] = np.int32
    for x in cat_names:
        dtypes[x] = "hex"

    # Create an NVTabular Dataset from a CSV-file glob
    # file_list = glob.glob(os.path.join(INPUT_PATH, "day_*[!.gz]"))
    file_list = ['/data/test/day_0']
    dataset = nvt.Dataset(
        file_list,
        engine="csv",
        names=cols,
        part_size="128MB",
        sep="\t",
        dtypes=dtypes,
        # client=client,
    )

    dataset.to_parquet(
        os.path.join("/data", "criteo_parquet"),
        preserve_files=True,
    )
```

the Traceback is as the following:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/asyncio/tasks.py", line 695, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 299, in _
    await self.start()
  File "/usr/local/lib/python3.8/dist-packages/distributed/nanny.py", line 347, in start
    response = await self.instantiate()
  File "/usr/local/lib/python3.8/dist-packages/distributed/nanny.py", line 430, in instantiate
    result = await self.process.start()
  File "/usr/local/lib/python3.8/dist-packages/distributed/nanny.py", line 685, in start
    msg = await self._wait_until_connected(uid)
  File "/usr/local/lib/python3.8/dist-packages/distributed/nanny.py", line 803, in _wait_until_connected
    raise msg["exception"]
  File "/usr/local/lib/python3.8/dist-packages/distributed/nanny.py", line 869, in run
    await worker
  File "/usr/local/lib/python3.8/dist-packages/distributed/core.py", line 299, in _
    await self.start()
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 1372, in start
    raise plugins_exceptions[0]
  File "/usr/local/lib/python3.8/dist-packages/distributed/worker.py", line 3248, in plugin_add
    result = plugin.setup(worker=self)
  File "/usr/local/lib/python3.8/dist-packages/dask_cuda/utils.py", line 78, in setup
    rmm.reinitialize(
  File "/usr/local/lib/python3.8/dist-packages/rmm/rmm.py", line 84, in reinitialize
    rmm.mr._initialize(
  File "rmm/_lib/memory_resource.pyx", line 674, in rmm._lib.memory_resource._initialize
  File "rmm/_lib/memory_resource.pyx", line 734, in rmm._lib.memory_resource._initialize
  File "rmm/_lib/memory_resource.pyx", line 272, in rmm._lib.memory_resource.PoolMemoryResource.__cinit__
MemoryError: std::bad_alloc: out_of_memory: RMM failure at:/usr/include/rmm/mr/device/pool_memory_resource.hpp:183: Maximum pool size exceeded
Task exception was never retrieved
future: <Task finished name='Task-33' coro=<_wrap_awaitable() done, defined at /usr/lib/python3.8/asyncio/tasks.py:688> exception=MemoryError('std::bad_alloc: out_of_memory: RMM failure at:/usr/include/rmm/mr/device/pool_memory_resource.hpp:183: Maximum pool size exceeded')>

```

It seems that the LocalCUDACluster reserves memory for different processes on the same GPU.
How can I fix this problem?

**Comment by madsbk** [comment]
> It seems that the LocalCUDACluster reserves memory for different processes on the same GPU.
How can I fix this problem?

It shouldn't do that. What you try without a RMM pool like:
```python
    cluster = LocalCUDACluster(
        protocol="tcp",
        local_directory=dask_workdir,
    )
```
And with a RMM pool:
```python
    cluster = LocalCUDACluster(
        protocol="tcp",
        local_directory=dask_workdir,
        rmm_pool_size=get_rmm_size(device_pool_frac * device_size),
    )
```

**Comment by zxgx** [comment]
When I run above script with setting CUDA_VISIBLE_DEVICES=0, it runs successfully in about one minutes.

But I want to fully use all 8 GPUs in my server, so I've tried this setting:
```
cluster = LocalCUDACluster(
        protocol="tcp",
        local_directory=dask_workdir,
    )
```
and it results in the same problem. All eight processes use the same GPU, and it cannot exit successfully.
![image](https://user-images.githubusercontent.com/34452939/183836978-815c7950-8bea-4000-8407-6702f036253c.png)

**Comment by zxgx** [comment]
The latter setting would result in the `Maximum pool size exceeded` error and couldn't run the code.

**Comment by madsbk** [comment]
Try this and make sure `CUDA_VISIBLE_DEVICES` isn't defined in the environment.
```python
    cluster = LocalCUDACluster(
        protocol="tcp",
        CUDA_VISIBLE_DEVICES="1, 2"  # Notice, this should be a string
        local_directory=dask_workdir,
    )
```

**Comment by zxgx** [comment]
Thanks for your kind comments.

I've found all the errors come from the dependency issues inside the [merlin-pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch) container:sweat_smile:. 
I adopt another container [merlin-pytorch-training](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch-training), and everything works fine.

**Comment by madsbk** [comment]
> Thanks for your kind comments.
> 
> I've found all the errors come from the dependency issues inside the [merlin-pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch) containersweat_smile. I adopt another container [merlin-pytorch-training](https://catalog.ngc.nvidia.com/orgs/nvidia/teams/merlin/containers/merlin-pytorch-training), and everything works fine.

Awesome :)
BTW, `CUDA_VISIBLE_DEVICES` is allowed to be a list so `range(len(numba.cuda.gpus))` should work.
